import type { AppLocale } from "@/hooks/use-locale";

/** Shared UI strings — keys must match exact English source text in the app. */
export type UiDict = Record<string, string>;

export const orDict: UiDict = {
  "Divinity Harmony": "ଦିବ୍ୟ ସାମରସ",
  Home: "ମୁଖ୍ୟ ପୃଷ୍ଠା",
  Mantras: "ମନ୍ତ୍ର",
  "Live Darshan": "ଲାଇଭ ଦର୍ଶନ",
  Scriptures: "ପବିତ୍ର ଗ୍ରନ୍ଥ",
  Deities: "ଦେବତା",
  Temples: "ମନ୍ଦିର",
  Priests: "ପୁରୋହିତ",
  Explore: "ଅନ୍ୱେଷଣ",
  Login: "ଲଗଇନ",
  Settings: "ସେଟିଂସ",
  Language: "ଭାଷା",
  English: "ଇଂରାଜୀ",
  "Application language": "ଆପ୍‌ର ଭାଷା",
  "Elder Mode": "ବୟସ୍କ ମୋଡ",
  "My Dharma": "ମୋ ଧର୍ମ",
  "Culture of India": "ଭାରତର ସଂସ୍କୃତି",
  "Pravachan & Reading": "ପ୍ରବଚନ ଓ ପଠନ",
  "Vedic Astrology": "ବୈଦିକ ଜ୍ୟୋତିଷ",
  "Mantra Library": "ମନ୍ତ୍ର ଭଣ୍ଡାର",
  "Sacred Mantras": "ପବିତ୍ର ମନ୍ତ୍ର",
  "A living devotional library": "ଏକ ଜୀବନ୍ତ ଭକ୍ତି ଭଣ୍ଡାର",
  "No mantra found. Try another spelling or deity.":
    "କୌଣସି ମନ୍ତ୍ର ମିଳିଲା ନାହିଁ। ଅନ୍ୟ ନାମ କିମ୍ବା ଦେବତା ଚେଷ୍ଟା କରନ୍ତୁ।",
  "Search current contact details": "ସାମ୍ପ୍ରତିକ ଯୋଗାଯୋଗ ବିବରଣୀ ଖୋଜନ୍ତୁ",
  "Find near me": "ମୋ ନିକଟରେ ଖୋଜନ୍ତୁ",
  "Google Maps": "ଗୁଗଲ୍ ମାନଚିତ୍ର",
  "Public directory": "ସାର୍ବଜନୀନ ନିର୍ଦ୍ଦେଶିକା",
  "Today’s practice": "ଆଜିର ସାଧନା",
  "My tradition profile": "ମୋ ପରମ୍ପରା ପ୍ରୋଫାଇଲ",
  "Current state": "ବର୍ତ୍ତମାନ ରାଜ୍ୟ",
  "Home state / cultural tradition": "ମୂଳ ରାଜ୍ୟ / ସାଂସ୍କୃତିକ ପରମ୍ପରା",
  "Preferred language": "ପସନ୍ଦ ଭାଷା",
  "Calendar tradition": "ପଞ୍ଜିକା ପରମ୍ପରା",
  "Save My Dharma": "ମୋ ଧର୍ମ ସଞ୍ଚୟ କରନ୍ତୁ",
  "Family ritual reminders": "ପାରିବାରିକ ଆଚରଣ ସ୍ମାରକ",
  "No family dates saved yet. Data remains in this browser.":
    "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପାରିବାରିକ ତାରିଖ ସଞ୍ଚୟ ହୋଇନାହିଁ। ତଥ୍ୟ ଏହି ବ୍ରାଉଜରରେ ରହିବ।",
  "Light the lamp": "ଦୀପ ଜ୍ୱଳନ୍ତୁ",
  "Ganesha invocation": "ଗଣେଶ ଆବାହନ",
  "Ishta-devata mantra": "ଇଷ୍ଟଦେବତା ମନ୍ତ୍ର",
  "One scripture verse": "ଗୋଟିଏ ଶାସ୍ତ୍ର ଶ୍ଲୋକ",
  "Japa practice": "ଜପ ସାଧନା",
  "Aarti and closing prayer": "ଆରତି ଓ ସମାପନ ପ୍ରାର୍ଥନା",
  Observances: "ଆଚରଣ",
  "Living traditions": "ଜୀବନ୍ତ ପରମ୍ପରା",
  "Pravachan guide": "ପ୍ରବଚନ ମାର୍ଗଦର୍ଶିକା",
  "Dharmic reading room": "ଧାର୍ମିକ ପଠନ କକ୍ଷ",
  "Official sources": "ଅଧିକୃତ ଉତ୍ସ",
  "Publisher-direct": "ପ୍ରକାଶକଙ୍କ ସିଧା ଉତ୍ସ",
  "Vedic Astrology Learning Centre": "ବୈଦିକ ଜ୍ୟୋତିଷ ଶିକ୍ଷା କେନ୍ଦ୍ର",
  "Private birth details": "ବ୍ୟକ୍ତିଗତ ଜନ୍ମ ବିବରଣୀ",
  "Date of birth": "ଜନ୍ମ ତାରିଖ",
  "Exact birth time": "ସଠିକ ଜନ୍ମ ସମୟ",
  "Birth place": "ଜନ୍ମ ସ୍ଥାନ",
  "Save privately on this device": "ଏହି ଉପକରଣରେ ବ୍ୟକ୍ତିଗତ ଭାବେ ସଞ୍ଚୟ",
  "Core calculation vocabulary": "ମୂଳ ଗଣନା ଶବ୍ଦାବଳୀ",
  "Navagraha study map": "ନବଗ୍ରହ ଅଧ୍ୟୟନ ମାନଚିତ୍ର",
  "Search YouTube": "YouTube ରେ ଖୋଜନ୍ତୁ",
  "Play recording": "ରେକର୍ଡିଂ ଚଲାନ୍ତୁ",
  "Devotional audio": "ଭକ୍ତି ଅଡ଼ିଓ",
  "Search mantra library": "ମନ୍ତ୍ର ଭଣ୍ଡାର ଖୋଜନ୍ତୁ",
  All: "ସବୁ",
  "Translation:": "ଅନୁବାଦ:",
  "Explain this mantra": "ଏହି ମନ୍ତ୍ର ବୁଝାନ୍ତୁ",
  "Meaning and context:": "ଅର୍ଥ ଓ ପ୍ରସଙ୍ଗ:",
  "Favorite mantra": "ପସନ୍ଦର ମନ୍ତ୍ର",
  "Newsletter email": "ନ୍ୟୁଜଲେଟର ଇମେଲ",
  Subscribe: "ସଦସ୍ୟ ହୁଅନ୍ତୁ",
  "Privacy policy": "ଗୋପନୀୟତା ନୀତି",
  "Terms of use": "ବ୍ୟବହାର ନିୟମ",
  Accessibility: "ସୁଗମତା",
  "Trust & support": "ବିଶ୍ୱାସ ଓ ସହାୟତା",
  Practice: "ସାଧନା",
  Discover: "ଅନ୍ୱେଷଣ",
  "Your account": "ଆପଣଙ୍କ ଖାତା",
  "User Settings": "ଉପଯୋଗକର୍ତ୍ତା ସେଟିଂସ",
  Profile: "ପ୍ରୋଫାଇଲ",
  Preferences: "ପସନ୍ଦ",
  Account: "ଖାତା",
  "Display name": "ପ୍ରଦର୍ଶିତ ନାମ",
  "Dark theme": "ଗାଢ଼ ଥିମ",
  "Logged Out": "ଲଗଆଉଟ ହୋଇଛି",
  "You have been successfully logged out.": "ଆପଣ ସଫଳତାର ସହ ଲଗଆଉଟ ହୋଇଛନ୍ତି।",
  "Three living paths. One sacred space.": "ତିନି ଜୀବନ୍ତ ପଥ। ଗୋଟିଏ ପବିତ୍ର ସ୍ଥାନ।",
  "Your spiritual library": "ଆପଣଙ୍କ ଆଧ୍ୟାତ୍ମିକ ଭଣ୍ଡାର",
  "Find what speaks to your heart.": "ଆପଣଙ୍କ ହୃଦୟ ସହ କଥା ହେଉଥିବା ଖୋଜନ୍ତୁ।",
  "Choose the moment you need.": "ଆପଣଙ୍କ ଆବଶ୍ୟକ ମୁହୂର୍ତ୍ତ ବାଛନ୍ତୁ।",
  "A sacred rhythm for every day": "ପ୍ରତିଦିନ ପାଇଁ ଗୋଟିଏ ପବିତ୍ର ତାଳ",
  "Live Temple Darshan": "ଲାଇଭ ମନ୍ଦିର ଦର୍ଶନ",
  "Welcome back": "ପୁନର୍ବାର ସ୍ୱାଗତ",
  "Create account": "ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ",
  "Sign in": "ସାଇନ ଇନ",
  "Continue as guest": "ଅତିଥି ଭାବେ ଜାରି ରଖନ୍ତୁ",
  "matching prayers": "ମିଳୁଥିବା ପ୍ରାର୍ଥନା",
  "Search Shiva, Krishna, peace…": "ଶିବ, କୃଷ୍ଣ, ଶାନ୍ତି ଖୋଜନ୍ତୁ…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ ପ୍ରାର୍ଥନା, ବେଦ ସ୍ତୋତ୍ର ଓ ମନ୍ତ୍ର ଅନ୍ୱେଷଣ କରନ୍ତୁ। ଦେବତା, ପାଠ କିମ୍ବା ଉଦ୍ଦେଶ୍ୟ ଅନୁସାରେ ଖୋଜନ୍ତୁ।",
  Logout: "ଲଗଆଉଟ",
};

export const bnDict: UiDict = {
  "Divinity Harmony": "দিব্য সামরস",
  Home: "প্রধান পাতা",
  Mantras: "মন্ত্র",
  "Live Darshan": "লাইভ দর্শন",
  Scriptures: "পবিত্র গ্রন্থ",
  Deities: "দেবতা",
  Temples: "মন্দির",
  Priests: "পুরোহিত",
  Explore: "অন্বেষণ",
  Login: "লগইন",
  Settings: "সেটিংস",
  Language: "ভাষা",
  English: "ইংরেজি",
  "Application language": "অ্যাপের ভাষা",
  "Elder Mode": "বয়স্ক মোড",
  "My Dharma": "আমার ধর্ম",
  "Culture of India": "ভারতের সংস্কৃতি",
  "Pravachan & Reading": "প্রবচন ও পাঠ",
  "Vedic Astrology": "বৈদিক জ্যোতিষ",
  "Mantra Library": "মন্ত্র ভাণ্ডার",
  "Sacred Mantras": "পবিত্র মন্ত্র",
  "A living devotional library": "একটি জীবন্ত ভক্তি ভাণ্ডার",
  "No mantra found. Try another spelling or deity.":
    "কোনো মন্ত্র পাওয়া যায়নি। অন্য নাম বা দেবতা চেষ্টা করুন।",
  All: "সব",
  "Your account": "আপনার অ্যাকাউন্ট",
  "User Settings": "ব্যবহারকারী সেটিংস",
  Profile: "প্রোফাইল",
  Preferences: "পছন্দ",
  Account: "অ্যাকাউন্ট",
  "Display name": "প্রদর্শিত নাম",
  "Dark theme": "গাঢ় থিম",
  "Logged Out": "লগ আউট হয়েছে",
  "You have been successfully logged out.": "আপনি সফলভাবে লগ আউট হয়েছেন।",
  "matching prayers": "মিলে যাওয়া প্রার্থনা",
  "Search Shiva, Krishna, peace…": "শিব, কৃষ্ণ, শান্তি খুঁজুন…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ প্রার্থনা, বৈদিক স্তোত্র ও মন্ত্র অন্বেষণ করুন। দেবতা, পাঠ বা উদ্দেশ্য অনুযায়ী খুঁজুন।",
  Logout: "লগ আউট",
};

export const guDict: UiDict = {
  "Divinity Harmony": "દિવ્ય સામરસ",
  Home: "મુખ્ય પૃષ્ઠ",
  Mantras: "મંત્ર",
  "Live Darshan": "લાઇવ દર્શન",
  Scriptures: "પવિત્ર ગ્રંથ",
  Deities: "દેવતાઓ",
  Temples: "મંદિર",
  Priests: "પuroહિત",
  Explore: "શોધ",
  Login: "લૉગિન",
  Settings: "સેટિંગ્સ",
  Language: "ભાષા",
  English: "અંગ્રેજી",
  "Application language": "એપની ભાષા",
  "Elder Mode": "વૃદ્ધ મોડ",
  "My Dharma": "મારો ધર્મ",
  "Culture of India": "ભારતની સંસ્કૃતિ",
  "Pravachan & Reading": "પ્રવચન અને વાંચન",
  "Vedic Astrology": "વૈદિક જ્યોતિષ",
  "Mantra Library": "મંત્ર પustakalaya",
  "Sacred Mantras": "પવિત્ર મંત્ર",
  "A living devotional library": "જીવંત ભક્તિ પustakalaya",
  "No mantra found. Try another spelling or deity.":
    "કોઈ મંત્ર મળ્યો નહીં. બીજું નામ અથવા દેવતા અજમાવો.",
  All: "બધા",
  "matching prayers": "મળતા મંત્ર",
  "Search Shiva, Krishna, peace…": "શિવ, કૃષ્ણ, શાંતિ શોધો…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ પ્રાર્થનાઓ, વેદ સ્તોત્ર અને મંત્ર શોધો. દેવતા, પાઠ અથવા હેતુ અનુસાર શોધો.",
  Logout: "લૉગ આઉટ",
};

export const mrDict: UiDict = {
  "Divinity Harmony": "दिव्य सामरस",
  Home: "मुख्यपृष्ठ",
  Mantras: "मंत्र",
  "Live Darshan": "थेट दर्शन",
  Scriptures: "पवित्र ग्रंथ",
  Deities: "देवता",
  Temples: "मंदिरे",
  Priests: "पुजारी",
  Explore: "शोध",
  Login: "लॉग इन",
  Settings: "सेटिंग्ज",
  Language: "भाषा",
  English: "इंग्रजी",
  "Application language": "अॅपची भाषा",
  "Elder Mode": "ज्येष्ठ मोड",
  "My Dharma": "माझा धर्म",
  "Culture of India": "भारताची संस्कृती",
  "Pravachan & Reading": "प्रवचन आणि वाचन",
  "Vedic Astrology": "वैदिक ज्योतिष",
  "Mantra Library": "मंत्र वाचनालय",
  "Sacred Mantras": "पवित्र मंत्र",
  "A living devotional library": "जिवंत भक्ती वाचनालय",
  "No mantra found. Try another spelling or deity.":
    "मंत्र सापडला नाही. दुसरे नाव किंवा देवता वापरून पहा.",
  All: "सर्व",
  "matching prayers": "जुळणारी प्रार्थना",
  "Search Shiva, Krishna, peace…": "शिव, कृष्ण, शांती शोधा…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ प्रार्थना, वैदिक स्तोत्रे आणि मंत्र शोधा. देवता, मजकूर किंवा हेतूनुसार शोधा.",
  Logout: "लॉग आउट",
};

export const taDict: UiDict = {
  "Divinity Harmony": "திவ்ய சாமரசம்",
  Home: "முகப்பு",
  Mantras: "மந்திரங்கள்",
  "Live Darshan": "நேரடி தarshan",
  Scriptures: "புனித நூல்கள்",
  Deities: "தெய்வங்கள்",
  Temples: "கோயில்கள்",
  Priests: "பurohitங்கள்",
  Explore: "ஆராயுங்கள்",
  Login: "உள்நுழை",
  Settings: "அமைப்புகள்",
  Language: "மொழி",
  English: "ஆங்கிலம்",
  "Application language": "பயன்பாட்டு மொழி",
  "Elder Mode": "முதியோர் பயன்முறை",
  "My Dharma": "என் தharma",
  "Culture of India": "இந்தியாவின் கலாச்சாரம்",
  "Pravachan & Reading": "பிரavachan & வாசிப்பு",
  "Vedic Astrology": "வேத ஜyotish",
  "Mantra Library": "மந்திர நூலகம்",
  "Sacred Mantras": "புனித மந்திரங்கள்",
  "A living devotional library": "உயிரோட்டமான பக்தி நூலகம்",
  "No mantra found. Try another spelling or deity.":
    "மந்திரம் கிடைக்கவில்லை. வேறு பெயர் அல்லது தெய்வத்தை முயற்சிக்கவும்.",
  All: "அனைத்தும்",
  "matching prayers": "பொருந்தும் பிரார்த்தனைகள்",
  "Search Shiva, Krishna, peace…": "சிவன், கrishna, அமைதி தேடுங்கள்…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ பிரார்த்தனைகள், வேத ஸ்தோத்திரங்கள் மற்றும் மந்திரங்களை ஆராயுங்கள்.",
  Logout: "வெளியேறு",
};

export const teDict: UiDict = {
  "Divinity Harmony": "దివ్య సామరస్యం",
  Home: "మुख్య పేజీ",
  Mantras: "మంత్రాలు",
  "Live Darshan": "లైve darshan",
  Scriptures: "పవిత్ర గ్రంథాలు",
  Deities: "దేవతలు",
  Temples: "దేవాలయాలు",
  Priests: "పurohitulu",
  Explore: "అన్వేషించండి",
  Login: "లాగిన్",
  Settings: "సెట్టింగ్‌లు",
  Language: "భాష",
  English: "ఇంగ్లీష్",
  "Application language": "యాప్ భాష",
  "Elder Mode": "వృద్ధుల మోడ్",
  "My Dharma": "నా ధర్మం",
  "Culture of India": "భారత సంస్కృతి",
  "Pravachan & Reading": "పravachan & చదవడం",
  "Vedic Astrology": "వేద జyotish",
  "Mantra Library": "మంత్ర గ్రంథాలయం",
  "Sacred Mantras": "పవిత్ర మంత్రాలు",
  "A living devotional library": "జీవant bhakti library",
  "No mantra found. Try another spelling or deity.":
    "మంత్రం కనుగొనబడలేదు. వేరే పేరు లేదా దేవతను ప్రయత్నించండి.",
  All: "అన్నీ",
  "matching prayers": "సరిపోలే ప్రార్థనలు",
  "Search Shiva, Krishna, peace…": "శివ, కrishna, శanti వెతకండి…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ ప్రార్థనలు, వేద స్తోత్రాలు మరియు మంత్రాలను అన్వేషించండి.",
  Logout: "లాగ్ అవుట్",
};

export const mlDict: UiDict = {
  "Divinity Harmony": "ദിവ്യ സാമരസ്യം",
  Home: "ഹോം",
  Mantras: "മന്ത്രങ്ങൾ",
  "Live Darshan": "ലൈവ് ദർശനം",
  Scriptures: "പവിത്ര ഗ്രന്ഥങ്ങൾ",
  Deities: "ദेवതകൾ",
  Temples: "ക്ഷേത്രങ്ങൾ",
  Priests: "പurohitar",
  Explore: "പര്യവേക്ഷണം",
  Login: "ലോഗിൻ",
  Settings: "ക്രമീകരണങ്ങൾ",
  Language: "ഭാഷ",
  English: "ഇംഗ്ലീഷ്",
  "Application language": "ആപ്പ് ഭാഷ",
  "Elder Mode": "മുതിർന്നവർ മോഡ്",
  "My Dharma": "എന്റെ ധarm",
  "Culture of India": "ഇന്ത്യയുടെ സംസ്കാരം",
  "Pravachan & Reading": "പravachan & വായന",
  "Vedic Astrology": "വേദ ജyotish",
  "Mantra Library": "മന്ത്ര ലൈbrary",
  "Sacred Mantras": "പവിത്ര മന്ത്രങ്ങൾ",
  "A living devotional library": "ജീവant bhakti library",
  "No mantra found. Try another spelling or deity.":
    "മന്ത്രം കണ്ടെത്തിയില്ല. മറ്റൊരു പേരോ ദേവതയോ ശ്രമിക്കുക.",
  All: "എല്ലാം",
  "matching prayers": "പൊരുത്തപ്പെടുന്ന പ്രാർത്ഥനകൾ",
  "Search Shiva, Krishna, peace…": "ശിവൻ, കrishna, സants…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ പ്രാർത്ഥനകൾ, വേദ സ്തോത്രങ്ങൾ, മന്ത്രങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക.",
  Logout: "ലോഗ് ഔട്ട്",
};

export const paDict: UiDict = {
  "Divinity Harmony": "ਦਿਵ्य ਸਾਮਰਸ",
  Home: "ਮੁੱਖ ਪੰਨਾ",
  Mantras: "ਮੰਤਰ",
  "Live Darshan": "ਲਾਈਵ ਦਰਸ਼ਨ",
  Scriptures: "ਪਵਿੱਤਰ ਗ੍ਰੰਥ",
  Deities: "ਦੇਵਤੇ",
  Temples: "ਮੰਦਰ",
  Priests: "pujari",
  Explore: "ਖੋਜ",
  Login: "ਲਾਗਇਨ",
  Settings: "ਸੈਟਿੰਗਾਂ",
  Language: "ਭਾਸ਼ਾ",
  English: "ਅੰਗਰੇਜ਼ੀ",
  "Application language": "ਐਪ ਦੀ ਭਾਸ਼ਾ",
  "Elder Mode": "ਬਜ਼ੁਰਗ ਮੋਡ",
  "My Dharma": "ਮera dharma",
  "Culture of India": "ਭਾਰਤ ਦੀ ਸanskruti",
  "Pravachan & Reading": "ਪravachan & ਪੜ੍ਹna",
  "Vedic Astrology": "ਵedic jyotish",
  "Mantra Library": "ਮੰਤਰ ਲਾਇbrary",
  "Sacred Mantras": "ਪਵਿੱਤਰ ਮੰਤਰ",
  "A living devotional library": "ਜੀਵant bhakti library",
  "No mantra found. Try another spelling or deity.":
    "ਕੋਈ ਮੰਤਰ ਨਹੀਂ ਮਿਲਿਆ। ਹੋਰ ਨਾਮ ਜਾਂ ਦੇਵਤਾ ਅਜ਼ਮਾਓ।",
  All: "ਸਾਰੇ",
  "matching prayers": "ਮੇਲ ਖਾਂਦੀਆਂ ਅਰਦਾਸਾਂ",
  "Search Shiva, Krishna, peace…": "ਸ਼ਿਵ, ਕrishna, ਸanti…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ ਅਰਦਾਸਾਂ, ਵੇਦ ਸਤੋਤਰ ਅਤੇ ਮੰਤਰ ਖੋਜੋ।",
  Logout: "ਲਾਗਆਉਟ",
};

export const asDict: UiDict = {
  "Divinity Harmony": "দিব্য সামৰস",
  Home: "মূল পৃষ্ঠা",
  Mantras: "মন্ত্ৰ",
  "Live Darshan": "লাইভ দৰ্শন",
  Scriptures: "পৱিত্ৰ গ্ৰন্থ",
  Deities: "দেৱতা",
  Temples: "মন্দিৰ",
  Priests: "পুৰোহিত",
  Explore: "অন্বেষণ",
  Login: "লগইন",
  Settings: "ছেটিংছ",
  Language: "ভাষা",
  English: "ইংৰাজী",
  "Application language": "এপৰ ভাষা",
  "Elder Mode": "বয়স্ক ম'ড",
  "My Dharma": "মোৰ ধৰ্ম",
  "Culture of India": "ভাৰতৰ সংস্কৃতি",
  "Pravachan & Reading": "প্ৰৱচন আৰু পঠন",
  "Vedic Astrology": "বৈদিক জyotish",
  "Mantra Library": "মন্ত্ৰ ভাণ্ডাৰ",
  "Sacred Mantras": "পৱিত্ৰ মন্ত্ৰ",
  "A living devotional library": "এটা জীৱন্ত ভক্তি ভাণ্ডাৰ",
  "No mantra found. Try another spelling or deity.":
    "কোনো মন্ত্ৰ পোৱা নগ'ল। আন নাম বা দেৱতা চেষ্টা কৰক।",
  All: "সকলো",
  "matching prayers": "মিলা প্ৰাৰ্থনা",
  "Search Shiva, Krishna, peace…": "শিব, কrishna, শanti…",
  "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.":
    "{count}+ প্ৰাৰ্থনা, বৈদিক স্তোত্ৰ আৰু মন্ত্ৰ অন্বেষণ কৰক।",
  Logout: "লগ আউট",
};

/** Locales with full or partial UI dictionaries (excluding en, hi, kn in main file). */
export const regionalUiDicts: Partial<Record<AppLocale, UiDict>> = {
  or: orDict,
  bn: bnDict,
  gu: guDict,
  mr: mrDict,
  ta: taDict,
  te: teDict,
  ml: mlDict,
  pa: paDict,
  as: asDict,
};
