/** Canonical English UI strings — semantic id → exact source text in the app. */
export const UI_KEYS = {
  divinityHarmony: "Divinity Harmony",
  home: "Home",
  mantras: "Mantras",
  liveDarshan: "Live Darshan",
  scriptures: "Scriptures",
  deities: "Deities",
  temples: "Temples",
  priests: "Priests",
  explore: "Explore",
  login: "Login",
  settings: "Settings",
  language: "Language",
  english: "English",
  applicationLanguage: "Application language",
  elderMode: "Elder Mode",
  myDharma: "My Dharma",
  cultureOfIndia: "Culture of India",
  pravachanReading: "Pravachan & Reading",
  vedicAstrology: "Vedic Astrology",
  mantraLibrary: "Mantra Library",
  sacredMantras: "Sacred Mantras",
  livingDevotionalLibrary: "A living devotional library",
  noMantraFound:
    "No mantra found. Try another spelling or deity.",
  searchContactDetails: "Search current contact details",
  findNearMe: "Find near me",
  googleMaps: "Google Maps",
  publicDirectory: "Public directory",
  todaysPractice: "Today’s practice",
  myTraditionProfile: "My tradition profile",
  currentState: "Current state",
  homeStateTradition: "Home state / cultural tradition",
  preferredLanguage: "Preferred language",
  calendarTradition: "Calendar tradition",
  saveMyDharma: "Save My Dharma",
  familyRitualReminders: "Family ritual reminders",
  noFamilyDatesSaved:
    "No family dates saved yet. Data remains in this browser.",
  lightTheLamp: "Light the lamp",
  ganeshaInvocation: "Ganesha invocation",
  ishtaDevataMantra: "Ishta-devata mantra",
  oneScriptureVerse: "One scripture verse",
  japaPractice: "Japa practice",
  aartiClosingPrayer: "Aarti and closing prayer",
  observances: "Observances",
  livingTraditions: "Living traditions",
  pravachanGuide: "Pravachan guide",
  dharmicReadingRoom: "Dharmic reading room",
  officialSources: "Official sources",
  publisherDirect: "Publisher-direct",
  vedicAstrologyCentre: "Vedic Astrology Learning Centre",
  privateBirthDetails: "Private birth details",
  dateOfBirth: "Date of birth",
  exactBirthTime: "Exact birth time",
  birthPlace: "Birth place",
  savePrivatelyOnDevice: "Save privately on this device",
  coreCalculationVocabulary: "Core calculation vocabulary",
  navagrahaStudyMap: "Navagraha study map",
  searchYouTube: "Search YouTube",
  playRecording: "Play recording",
  devotionalAudio: "Devotional audio",
  searchMantraLibrary: "Search mantra library",
  all: "All",
  translationLabel: "Translation:",
  explainThisMantra: "Explain this mantra",
  meaningAndContext: "Meaning and context:",
  favoriteMantra: "Favorite mantra",
  newsletterEmail: "Newsletter email",
  subscribe: "Subscribe",
  privacyPolicy: "Privacy policy",
  termsOfUse: "Terms of use",
  accessibility: "Accessibility",
  trustAndSupport: "Trust & support",
  practice: "Practice",
  discover: "Discover",
  yourAccount: "Your account",
  userSettings: "User Settings",
  profile: "Profile",
  preferences: "Preferences",
  account: "Account",
  displayName: "Display name",
  darkTheme: "Dark theme",
  loggedOut: "Logged Out",
  loggedOutSuccess: "You have been successfully logged out.",
  threeLivingPaths: "Three living paths. One sacred space.",
  yourSpiritualLibrary: "Your spiritual library",
  findWhatSpeaks: "Find what speaks to your heart.",
  chooseTheMoment: "Choose the moment you need.",
  sacredRhythmEveryDay: "A sacred rhythm for every day",
  liveTempleDarshan: "Live Temple Darshan",
  welcomeBack: "Welcome back",
  createAccount: "Create account",
  signIn: "Sign in",
  continueAsGuest: "Continue as guest",
  matchingPrayers: "matching prayers",
  searchMantraPlaceholder: "Search Shiva, Krishna, peace…",
  exploreMantrasTemplate:
    "Explore {count}+ prayers, Vedic hymns and stotras. Search by deity, text or intention.",
  logout: "Logout",
  myAccount: "My Account",
  signedIn: "Signed in",
  toggleTheme: "Toggle theme",
  devotee: "Devotee",
  appLanguage: "App language",
  appLanguageHint:
    "Changes menus and labels. Mantra Sanskrit text stays as written.",
  saveProfile: "Save profile",
  signOut: "Sign out",
  signInOrCreate: "Sign in or create account",
  guestPreferences: "Guest preferences remain on this browser.",
  appearanceAndPlayback: "Appearance and playback",
  autoplayMedia: "Autoplay media",
  notifications: "Notifications",
  accountSecurity: "Account security",
  gotraOptional: "Gotra or family tradition (optional)",
  yourNamePlaceholder: "Your name",
  enterIfKnown: "Enter only if known",
  ishtaKulaDevata: "Ishta or Kula Devata (optional)",
  chooseFamilyCalendar: "Choose your family calendar",
  signatureObservances: "Signature observances",
  traditionsAndTemples: "Traditions & temples",
  selectStateOrUt: "Select state or UT",
  add: "Add",
  deleteReminder: "Delete reminder",
  personalSpiritualHome: "Personal spiritual home",
  completedOnDevice: "completed on this device.",
  returnToHome: "Return to Home",
  pageNotFound: "Oops! Page not found",
  backHome: "Back home",
  beginWithMantra: "Begin with a mantra",
  watchLiveDarshan: "Watch live darshan",
  openLibrary: "Open library",
  todaysPanchang: "Today’s Panchang",
  dailyCalendar: "Daily calendar",
  useMyLocation: "Use my location",
  liveNow: "LIVE NOW",
  refreshLiveStatus: "Refresh live status",
  sacredTextsHeritage: "Sacred Texts & Hindu Heritage",
  readFullDetails: "Read full details",
  priestSearch: "Priest Search",
  digitalJapaMala: "Digital Japa Mala",
  reset: "Reset",
  closeFullImage: "Close full image",
  mantraScript: "Mantra script",
  useRegionalScript: "Use my regional script",
  explaining: "Explaining…",
  listenWithContext: "Listen with context",
  pravachanCulturalReading: "Pravachan & Cultural Reading Room",
  newsletterTagline: "A thoughtful note, occasionally",
  newsletterDesc:
    "New mantras, sacred-text additions and useful festival guidance—without daily noise.",
  emailAddressPlaceholder: "Email address",
  subscribeAgreement:
    "I agree to receive email updates. I can unsubscribe from any message.",
  footerTagline:
    "A calm digital space for mantra practice, temple darshan, Hindu sacred literature and everyday devotional learning.",
  supportTheProject: "Support the project",
  footerDisclaimer:
    "Educational devotional content · Verify muhurta and formal rites with a qualified regional source.",
  heroSubtitle: "A quieter space for your daily sacred journey.",
  heroDescription:
    "Listen to timeless mantras, experience live temple darshan, and study Hindu scriptures in one beautifully connected sanctuary.",
  sacredWisdomLiving: "Sacred wisdom · Living tradition",
  resources700: "700+ sacred resources",
  liveTempleDiscovery: "Live temple discovery",
  todaysIntention: "Today’s intention",
  peaceInEveryBreath: "Peace in every breath",
  readWisdom: "Read wisdom",
  chooseSoundDarshan:
    "Choose sound, darshan or scripture—each experience responds, updates and moves with you.",
  startListening: "Start listening",
  watchDarshan: "Watch darshan",
  readReflect: "Read & reflect",
  sacredTexts: "Sacred Texts",
  designedAroundYou: "Designed around you",
  listenReadReflect: "Listen · Read · Reflect",
  fastDiscovery: "Fast discovery",
  sanskritAndEnglish: "Sanskrit & English",
  morningPractice: "Morning practice",
  beginWithGayatri: "Begin with Gayatri",
  enterTheTemple: "Enter the temple",
  exploreTheGita: "Explore the Gita",
  backToDivinityHarmony: "Back to Divinity Harmony",
  practiceRemembered: "Your practice, remembered securely.",
  profileAcrossDevices:
    "Keep your profile, avatar and spiritual preferences connected across devices.",
  authPoweredBy: "Authentication and file storage powered by Supabase",
  authConfiguring: "Account service is being configured",
  guestAccessAvailable:
    "Guest access remains available. Add the Supabase deployment variables to enable login.",
  signInWithEmail: "Sign in with the email used for your account.",
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot password?",
  createYourAccount: "Create your account",
  profileFollowsDevices: "Your profile will follow you across devices.",
  minEightChars: "Minimum 8 characters.",
  emailConfirmationNote:
    "Email confirmation may be required by your Supabase project.",
  listenAndChant: "Listen & chant",
  templeBroadcasts: "Temple broadcasts",
  readSanskritJapa:
    "Read the Sanskrit, understand the meaning and continue your daily japa.",
  enterTempleStreams:
    "Enter temple streams that are being discovered and refreshed automatically.",
  exploreVedasHeritage:
    "Explore Vedas, Gitas, Puranas, philosophy, ancestry and Hindu heritage.",
  checkingLive: "checking live",
  liveNowLower: "live now",
  streamsFound: "streams found",
  mantrasMetric: "mantras",
  worksMetric: "works",
  moveNaturally:
    "Move naturally between sound, sacred image, meaning and source text. Every path remains calm and responsive across mobile and desktop.",
  searchHundredsResources: "Search hundreds of resources.",
  originalTextContext: "Original text and clear context.",
  noNoiseMenus:
    "No noise, no complicated menus—just a direct path to listening, darshan, and timeless knowledge.",
  gayatriDetail: "A luminous Vedic prayer for clarity and awakening.",
  discoverDarshanStreams:
    "Discover darshan streams currently broadcasting.",
  gitaReadingDetail:
    "Open source-backed chapters with a quiet reading view.",
  carryPractice: "Carry the practice with you.",
  loadingTodayDetails: "Loading today’s details…",
  panchangLocalized: "Panchang localized",
  nakshatra: "Nakshatra",
  tithi: "Tithi",
  yoga: "Yoga",
  karana: "Karana",
  starOf27: "Star {n} of 27",
  sunMoonCombination: "Sun–Moon combination",
  halfTithiDivision: "Half-tithi division",
  sunrise: "Sunrise",
  sunset: "Sunset",
  moon: "Moon",
  locationNotSupported: "Location is not supported by this browser.",
  locationPermissionDenied:
    "Location permission was not granted. Showing India overview.",
  panchangCalendarAlt: "Sun, moon and nakshatra celestial calendar",
  templePriestDirectory: "Temple & Priest Directory",
  pleaseConfirmSubscribe:
    "Please confirm that you want to receive email updates.",
  alreadySubscribed: "You are already subscribed.",
  welcomeSubscribed: "Welcome—your subscription is confirmed.",
  pleaseTryAgain: "Please try again.",
  liveLabel: "Live",
  astrologyIntro:
    "Astronomical calculations and traditional interpretations must be distinguished. This area teaches the system without fear-based predictions or automatic sales remedies.",
  birthPlacePlaceholder: "City, state, country",
  natalChartDisclaimer:
    "Charts use an educational sidereal approximation from your saved birth details. Confirm important decisions with a qualified jyotishi.",
  personalBirthSnapshot: "Your birth snapshot",
  moonSignAtBirth: "Moon sign (Rashi)",
  lagnaAtBirth: "Ascendant (Lagna)",
  birthTithiAtBirth: "Birth tithi",
  generatePersonalChart: "Generate personal chart",
  birthChartNeedsDateTime:
    "Enter birth date and time, then save or generate to see your personalized snapshot.",
  birthChartApproxNote:
    "Educational sidereal approximation from date, time and place — not ephemeris-grade muhurta software.",
  mapOfTempleTemplate: "Map of {name}",
  birthDetailsSaved: "Birth details saved",
  birthDetailsSavedDesc: "Your birth date, time and place stay privately on this device.",
  birthDetailsAutoFilled: "Birth place suggested from your location.",
  useMyLocationBirth: "Use my location for birth place",
  conceptRashi: "Rashi",
  conceptRashiDesc: "The zodiac sign occupied by a graha.",
  conceptLagna: "Lagna",
  conceptLagnaDesc: "The ascendant calculated from exact birth time and place.",
  conceptNakshatraJyotisha: "Nakshatra",
  conceptNakshatraJyotishaDesc:
    "One of 27 lunar mansions used in Panchang and Jyotisha.",
  conceptDasha: "Dasha",
  conceptDashaDesc:
    "A time-period framework; Vimshottari is one widely used system.",
  conceptGochara: "Gochara",
  conceptGocharaDesc: "Current planetary transits relative to a natal reference.",
  conceptAyanamsha: "Ayanamsha",
  conceptAyanamshaDesc:
    "The chosen sidereal offset; calculation settings must name it.",
  grahaSuryaVitality: "Surya · vitality",
  grahaChandraMind: "Chandra · mind",
  grahaMangalaAction: "Mangala · action",
  grahaBudhaIntellect: "Budha · intellect",
  grahaGuruWisdom: "Guru · wisdom",
  grahaShukraHarmony: "Shukra · harmony",
  grahaShaniDiscipline: "Shani · discipline",
  grahaRahuAmplification: "Rahu · amplification",
  grahaKetuRelease: "Ketu · release",
  panchangDisclaimer:
    "Daily spiritual overview based on date and location. Confirm exact muhurta and boundary times with a regional Panchang.",
  divineForms: "Divine forms",
  deityEncyclopediaDesc:
    "Explore sacred stories, visual symbols, festivals, mantras and connected scriptures.",
  allDeities: "All deities",
  iconographyAndSymbols: "Iconography and symbols",
  sacredFestivalsHeading: "Sacred festivals",
  relatedMantrasBtn: "Related mantras",
  readSacredLoreBtn: "Read sacred lore",
  sacredGeography: "Sacred geography",
  templeLocatorDesc:
    "Discover important Hindu temples and sort the curated directory by your location.",
  searchTemplePlaceholder: "Search temple, deity, city or state",
  typicalHoursLabel: "Typical hours",
  mapAttribution:
    "Map data © OpenStreetMap contributors. Temple hours change on festivals and local occasions; confirm directly before travel.",
  liveNowMultiSource: "LIVE NOW · MULTI-SOURCE DISCOVERY",
  liveDarshanIntro:
    "Current streams are discovered from YouTube live search and the LiveDarshanHub temple directory. There is no visitor API key, duplicate streams are removed, and results refresh every five minutes.",
  searchingLiveSources: "Searching live temple sources...",
  liveNowCountTemplate: "Live now ({count})",
  streamLiveNotice:
    "This stream was marked LIVE at the last refresh. Use judgement before donations or transactions.",
  sanatanaKnowledgeLibrary: "Sanatana knowledge library",
  sacredTextsLibraryDesc:
    "Explore a growing library covering Vedas, Upanishads, Puranas, Gitas, sacred narratives, philosophy, Hindu deities, Vedic hymns, temples, teachers, family dharma and ancestral traditions.",
  knowledgePathsTemplate: "{count} knowledge paths",
  resourcesCountTemplate: "{count} resources",
  showingResourcesTemplate: "Showing {shown} of {total} resources",
  manyCalendarsTagline: "Many calendars · many living traditions",
  cultureIndiaIntro:
    "Explore state and union-territory culture packs without forcing one regional practice onto every family.",
  searchCulturePlaceholder: "Search Karnataka, Jagannath, Durga Puja, Tamil…",
  culturePacksNoticeTemplate:
    "{count} regional culture packs. Editorial details identify traditions rather than declaring one universal ritual sequence.",
  templesLabelPrefix: "Temples",
  tapToCount: "tap to count",
  thisMalaTemplate: "{current}/108 this mala",
  roundsTemplate: "{count} rounds",
  manualScriptSelection:
    "Manual selection. This changes writing script, not the sacred wording.",
  spokenTextFallback:
    "Spoken-text fallback when a devotional recording is unavailable",
  audioCompactViewNote:
    "Audio-style compact view. The official YouTube player appears only after Play is pressed.",
  openScheduleLibrary: "Open current schedule/library",
  publisherCopyrightNote:
    "The app links to publishers and official organizations. Full copyrighted issues are included only through permission or an authorized feed.",
  regionalRitualGuidance: "Regional ritual guidance",
  priestHeroTitle: "Find a priest and understand the puja before you book",
  priestHeroDesc:
    "Search live local directories for current phone numbers, reviews and availability. Divinity Harmony does not copy unverified personal numbers.",
  searchPujaPlaceholder: "Search city, language, or puja",
  verifyDirectoryLinks:
    "Links open live Google Maps or Sulekha results so you can verify reviews and contact details.",
  backToCulturePacks: "All culture packs",
  viewCultureDetails: "View culture details",
  openExternalPravachan: "Open external pravachan",
  detectedStateTemplate: "Detected: {state}",
  library: "Library",
  matching: "matching",
  scriptChangesNote:
    "This changes writing script, not the sacred wording.",
  browserLanguage: "Browser language",
  manualSelection: "Manual selection",
  endOfLibrary: "End of library",
  startOfLibrary: "Start of library",
  explanationUnavailable: "Explanation unavailable right now.",
  explanationTempUnavailable: "Explanation temporarily unavailable.",
  regionalScriptApplied: "Regional script applied",
  locationUnavailableShort: "Location unavailable",
  usedBrowserLanguage: "Used browser language",
  detectedFromTemplate: "Detected from {label}",
  requestedDevotionalCollection: "Requested devotional collection",
  requestedDevotionalDesc:
    "Additional supplied titles with their original reading source.",
  searchScripturesPlaceholder:
    "Search Krishna, ancestors, Vedas, yoga, mantra...",
  noMatchingResource: "No matching resource in this category.",
  tryAnotherKeyword: "Try another keyword or switch category.",
  loadMoreResourcesTemplate: "Load {count} more resources",
  respectfulUseTitle: "Respectful use",
  respectfulUseNote:
    "Treat sacred texts with reverence. Verify critical passages with a qualified teacher or authorized edition.",
  sourceTextLabel: "Source text",
  detailedSourceArticle: "Detailed source article",
  loadingSourceText: "Loading the source text…",
  sourceErrorHint:
    "Try English, or use the study companion below while the source is temporarily unavailable.",
  sourceAndLicense: "Source & license",
  chooseChapterSection: "Choose chapter or section",
  studyCompanion: "Study companion",
  backgroundAndMeaning: "Background and meaning",
  whatResourceTeaches: "What this resource teaches",
  whyItMatters: "Why it matters",
  howToStudyIt: "How to study it",
  traditionAndInterpretation: "Tradition and interpretation",
  keyThemes: "Key themes",
  practiceNoteLabel: "Practice note:",
  categoryVedasVedangas: "Vedas & Vedangas",
  categoryUpanishads: "Upanishads",
  categoryPuranas: "Puranas",
  categoryGitas: "Gitas",
  categoryItihasaSacred: "Itihasa & Sacred Narratives",
  categoryPhilosophyYoga: "Philosophy & Yoga",
  categoryDeitiesSacredLore: "Deities & Sacred Lore",
  categoryAncestorsDharma: "Ancestors & Dharma",
  categoryHymnsMantras: "Hymns & Mantras",
  deityGanesha: "Ganesha",
  deityShiva: "Shiva",
  deityVishnuAvatars: "Vishnu & avatars",
  deityKrishna: "Krishna",
  deityDivineMother: "Divine Mother",
  deityLakshmi: "Lakshmi",
  deitySaraswati: "Saraswati",
  deityGayatri: "Gayatri",
  deityHanuman: "Hanuman",
  deityMurugan: "Murugan",
  deityVedicPlanetary: "Vedic & planetary",
  deityVedicUniversal: "Vedic & universal",
  myDharmaHeroDesc:
    "Keep current location, home culture and family practice separate. Your traditions stay with you even when you move.",
  reminderNamePlaceholder: "Shraddha, nakshatra birthday, vrata…",
  reminderNotePlaceholder: "Private family note",
  calendarNameTemplate: "{name} calendar",
  practiceCompletedTemplate: "{done} of {total} completed on this device.",
  pujaVidhiGuide: "Puja vidhi guide",
  materialsNeeded: "Materials needed",
  stepsLabel: "Steps",
  priestNoteLabel: "Priest note",
  purposeLabel: "Purpose",
  durationLabel: "Duration",
  priestsFoundTemplate: "{count} priests found",
  openPriestsNearMe: "Open priests near my current location",
  locationUnavailableBrowser: "Location is unavailable in this browser.",
  allowLocationPriests: "Allow location access to search near you.",
  cityPriestSearchTemplate: "{city} Priest Search",
  tapPlayToHear: "Tap Play to hear this mantra",
  deviceVoice: "Device voice",
  deviceVoiceFallback:
    "Uses your device voice when no recording is available.",
  previousTrack: "Previous track",
  nextTrack: "Next track",
  mute: "Mute",
  unmute: "Unmute",
  playingBelow: "Playing below",
  findAnotherRecording: "Find another recording",
  noRecordingFound:
    "No matching devotional recording was found right now.",
  recordingsUnavailable: "YouTube recordings are temporarily unavailable.",
  unableSignIn: "Unable to sign in",
  spiritualProfileReady: "Your spiritual profile is ready.",
  passwordTooShort: "Password is too short",
  useEightChars: "Use at least 8 characters.",
  unableCreateAccount: "Unable to create account",
  checkYourEmail: "Check your email",
  emailConfirmDesc:
    "Open the confirmation link — it will bring you back to mantra.sigq.in to finish verification.",
  enterEmailFirst: "Enter your email first",
  resetUnavailable: "Reset unavailable",
  passwordResetSent: "Password reset sent",
  checkInboxReset:
    "Check your inbox. The link opens mantra.sigq.in securely.",
  chapterUnavailable: "The selected chapter is unavailable.",
  pageNotFoundDesc: "The page you are looking for does not exist.",
  catalogAddedTemplate: "Added {count} verified catalog entries.",
  catalogFallbackNotice:
    "Using the built-in library while the optional catalog is unavailable.",
  noMantraText: "This mantra has no text to read aloud.",
  voiceUnsupported: "Voice playback is not supported in this browser.",
  loadingVoice: "Loading voice…",
  playingWithVoiceTemplate: "Playing with {name}.",
  playingWithDeviceVoice: "Playing with your device voice.",
  voicePlaybackFailed:
    "Could not start voice playback. Tap Play again or try Chrome/Edge on desktop.",
  seekAudio: "Seek audio",
  volumeLabel: "Volume",
  pauseLabel: "Pause",
  playLabel: "Play",
  audioPlayerLabel: "Audio player",
  profileUpdated: "Profile updated",
  profileSyncedDesc:
    "Your language and profile are synchronized across devices.",
  unableToSave: "Unable to save",
  guestProfileSaved: "Guest profile saved",
  guestSavedDesc:
    "Saved in this browser. Sign in to sync language and profile.",
  preferencesUpdated: "Preferences updated",
  syncProfilePhoto: "Synchronize your profile and photo",
  signInCrossDevice: "Sign in to use secure cross-device storage.",
  guestProfile: "Guest profile",
  authenticatedProfile: "Authenticated profile",
  profilePhotoAlt: "Profile photo",
  supabaseNotConfigured:
    "Supabase is not configured in this deployment. Add the two public environment variables described in the README.",
  accountConnectedSupabase:
    "Your account is connected securely through Supabase.",
  preferencesGuestNote:
    "These preferences remain available even when browsing as a guest.",
  darkThemeDesc: "Use the darker devotional palette.",
  autoplayMediaDesc: "Start available recordings automatically.",
  notificationsDesc: "Remember your notification preference.",
  sessionManagedSupabase:
    "Your session is managed and refreshed by Supabase Auth.",
  signInForSecurity: "Sign in to access account security.",
  userIdLabel: "User ID: {id}",
  avatarFileRequirement: "Choose a JPG, PNG or WebP under 2 MB",
  avatarUploadFailed: "Avatar upload failed",
  avatarUpdateFailed: "Avatar update failed",
  profilePhotoUpdated: "Profile photo updated",
  endOfLibraryDesc: "You have reached the final mantra.",
  startOfLibraryDesc: "You are at the first mantra.",
  noMatchingSacredResource: "No matching sacred resource",
  tryAllCategories: "Try another keyword or choose All categories.",
  respectfulUseLibraryNote:
    "This library provides educational overviews, not priestly or legal instruction. Ancestral rites, initiation practices and recitation rules vary by family, region and sampradaya; follow qualified family or tradition-specific guidance for ritual performance.",
  usedBrowserLanguageDesc: "Used your browser language instead.",
  pujaVidhiLibrary: "Puja Vidhi Library",
  materialsStepsCompletion: "Materials, steps and completion",
  pujaPrepareIntro:
    "Prepare properly and ask the right questions. Fire rites, samskaras, muhurta and lineage-specific procedures still require a qualified priest.",
  prepareLabel: "Prepare",
  traditionalSequence: "Traditional sequence",
  typicalDurationTemplate: "Typical duration: {duration}",
  noDirectoryMatches:
    "No directory matches that search. Try a nearby city or puja name.",
} as const;

export type UiKey = keyof typeof UI_KEYS;

export type UiLocale = Exclude<
  import("@/hooks/use-locale").AppLocale,
  "en"
>;

export type UiLocalePack = Record<UiKey, string>;
