/** Complete as UI pack — 186 semantic keys. */
export const as186 = {
  divinityHarmony: "দিব্য সামৰস",
  home: "মূল পৃষ্ঠা",
  mantras: "মন্ত্ৰ",
  liveDarshan: "লাইভ দৰ্শন",
  scriptures: "পৱিত্ৰ গ্ৰন্থ",
  deities: "দেৱতা",
  temples: "মন্দিৰ",
  priests: "পুৰোহিত",
  explore: "অন্বেষণ",
  login: "লগইন",
  settings: "ছেটিংছ",
  language: "ভাষা",
  english: "ইংৰাজী",
  applicationLanguage: "এপৰ ভাষা",
  elderMode: "বয়স্ক ম'ড",
  myDharma: "মোৰ ধৰ্ম",
  cultureOfIndia: "ভাৰতৰ সংস্কৃতি",
  pravachanReading: "প্ৰৱচন আৰু পঠন",
  vedicAstrology: "বৈদিক জ্যোতিষ",
  mantraLibrary: "মন্ত্ৰ ভাণ্ডাৰ",
  sacredMantras: "পৱিত্ৰ মন্ত্ৰ",
  livingDevotionalLibrary: "এটা জীৱন্ত ভক্তি ভাণ্ডাৰ",
  noMantraFound: "কোনো মন্ত্ৰ পোৱা নগ'ল। আন নাম বা দেৱতা চেষ্টা কৰক।",
  searchContactDetails: "সাম্প্ৰতিক যোগাযোগৰ বিৱৰণ বিচাৰক",
  findNearMe: "মোৰ ওচৰত বিচাৰক",
  googleMaps: "গুগল মানচিত্ৰ",
  publicDirectory: "সৰ্বজনীন নিৰ্দেশিকা",
  todaysPractice: "আজিৰ সাধনা",
  myTraditionProfile: "মোৰ পৰম্পৰা প্ৰ'ফাইল",
  currentState: "বৰ্তমান ৰাজ্য",
  homeStateTradition: "মূল ৰাজ্য / সাংস্কৃতিক পৰম্পৰা",
  preferredLanguage: "পছন্দৰ ভাষা",
  calendarTradition: "পঞ্জিকা পৰম্পৰা",
  saveMyDharma: "মোৰ ধৰ্ম সংৰক্ষণ কৰক",
  familyRitualReminders: "পাৰিবাৰিক ৰীতি-নীতিৰ স্মাৰক",
  noFamilyDatesSaved: "এপৰ্য্যন্ত কোনো পাৰিবাৰিক তাৰিখ সংৰক্ষিত নহয়। তথ্য এই ব্ৰাউজাৰত থাকিব।",
  lightTheLamp: "দীপ জ্বলাওক",
  ganeshaInvocation: "গণেশ আবাহন",
  ishtaDevataMantra: "ইষ্টদেৱতাৰ মন্ত্ৰ",
  oneScriptureVerse: "এটা শাস্ত্ৰৰ শ্লোক",
  japaPractice: "জপ সাধনা",
  aartiClosingPrayer: "আৰতি আৰু সমাপনী প্ৰাৰ্থনা",
  observances: "অনুষ্ঠান",
  livingTraditions: "জীৱন্ত পৰম্পৰা",
  pravachanGuide: "প্ৰৱচন নিৰ্দেশিকা",
  dharmicReadingRoom: "ধাৰ্মিক পঠন কক্ষ",
  officialSources: "অধিকাৰিক উৎস",
  publisherDirect: "প্ৰকাশক-সৰাসৰি",
  vedicAstrologyCentre: "বৈদিক জ্যোতিষ শিক্ষা কেন্দ্ৰ",
  privateBirthDetails: "ব্যক্তিগত জন্মৰ বিৱৰণ",
  dateOfBirth: "জন্ম তাৰিখ",
  exactBirthTime: "সঠিক জন্ম সময়",
  birthPlace: "জন্মস্থান",
  savePrivatelyOnDevice: "এই ডিভাইচত ব্যক্তিগতভাৱে সংৰক্ষণ কৰক",
  coreCalculationVocabulary: "মূল গণনাৰ শব্দভাণ্ডাৰ",
  navagrahaStudyMap: "নৱগ্ৰহ অধ্যয়ন মানচিত্ৰ",
  searchYouTube: "YouTube-ত বিচাৰক",
  playRecording: "ৰেকৰ্ডিং চলাওক",
  devotionalAudio: "ভক্তিমূলক অডিঅ'",
  searchMantraLibrary: "মন্ত্ৰ ভাণ্ডাৰ বিচাৰক",
  all: "সকলো",
  translationLabel: "অনুবাদ:",
  explainThisMantra: "এই মন্ত্ৰটো ব্যাখ্যা কৰক",
  meaningAndContext: "অৰ্থ আৰু প্ৰসঙ্গ:",
  favoriteMantra: "প্ৰিয় মন্ত্ৰ",
  newsletterEmail: "নিউজলেটাৰ ইমেইল",
  subscribe: "সদস্যতা লওক",
  privacyPolicy: "গোপনীয়তা নীতি",
  termsOfUse: "ব্যৱহাৰৰ চৰ্ত",
  accessibility: "সুগম্যতা",
  trustAndSupport: "বিশ্বাস আৰু সহায়",
  practice: "সাধনা",
  discover: "অন্বেষণ",
  yourAccount: "আপোনাৰ একাউণ্ট",
  userSettings: "ব্যৱহাৰকাৰী ছেটিংছ",
  profile: "প্ৰ'ফাইল",
  preferences: "পছন্দ",
  account: "একাউণ্ট",
  displayName: "প্ৰদৰ্শিত নাম",
  darkTheme: "গাঢ় থিম",
  loggedOut: "লগ আউট হ'ল",
  loggedOutSuccess: "আপুনি সফলতাৰে লগ আউট হ'ল।",
  threeLivingPaths: "তিনিটা জীৱন্ত পথ। এটা পৱিত্ৰ স্থান।",
  yourSpiritualLibrary: "আপোনাৰ আধ্যাত্মিক ভাণ্ডাৰ",
  findWhatSpeaks: "আপোনাৰ হৃদয়ত কথা কোৱাটো বিচাৰক।",
  chooseTheMoment: "আপোনাৰ প্ৰয়োজনীয় মুহূৰ্ত বাছক।",
  sacredRhythmEveryDay: "প্ৰতিদিনৰ বাবে এটা পৱিত্ৰ ছন্দ",
  liveTempleDarshan: "লাইভ মন্দিৰ দৰ্শন",
  welcomeBack: "পুনৰ স্বাগতম",
  createAccount: "একাউণ্ট সৃষ্টি কৰক",
  signIn: "ছাইন ইন",
  continueAsGuest: "অতিথি হিচাপে অব্যাহত ৰাখক",
  matchingPrayers: "মিলা প্ৰাৰ্থনা",
  searchMantraPlaceholder: "Shiva, Krishna, শান্তি বিচাৰক…",
  exploreMantrasTemplate: "{count}+ প্ৰাৰ্থনা, বৈদিক স্তোত্ৰ আৰু মন্ত্ৰ অন্বেষণ কৰক। দেৱতা, পাঠ বা উদ্দেশ্য অনুসৰি বিচাৰক।",
  logout: "লগ আউট",
  myAccount: "মোৰ একাউণ্ট",
  signedIn: "ছাইন ইন কৰা",
  toggleTheme: "থিম সলনি",
  devotee: "ভক্ত",
  appLanguage: "এপৰ ভাষা",
  appLanguageHint: "মেনু আৰু লেবেল সলনি কৰে। মন্ত্ৰৰ সংস্কৃত পাঠ যেনে আছে তেনেই থাকে।",
  saveProfile: "প্ৰ'ফাইল সংৰক্ষণ",
  signOut: "ছাইন আউট",
  signInOrCreate: "ছাইন ইন বা একাউণ্ট সৃষ্টি",
  guestPreferences: "অতিথিৰ পছন্দ এই ব্ৰাউজাৰত থাকিব।",
  appearanceAndPlayback: "দেখা আৰু প্লেবেক",
  autoplayMedia: "মিডিয়া স্বয়ংক্ৰিয় চলাওক",
  notifications: "জ্ঞাপন",
  accountSecurity: "একাউণ্ট সুৰক্ষা",
  gotraOptional: "গোত্ৰ বা পাৰিবাৰিক পৰম্পৰা (ঐচ্ছিক)",
  yourNamePlaceholder: "আপোনাৰ নাম",
  enterIfKnown: "জানিলে মাত্ৰ লিখক",
  ishtaKulaDevata: "ইষ্ট বা কুল দেৱতা (ঐচ্ছিক)",
  chooseFamilyCalendar: "আপোনাৰ পাৰিবাৰিক পঞ্জিকা বাছক",
  signatureObservances: "প্ৰধান অনুষ্ঠান",
  traditionsAndTemples: "পৰম্পৰা আৰু মন্দিৰ",
  selectStateOrUt: "ৰাজ্য বা কেন্দ্ৰীয় শাসিত অঞ্চল বাছক",
  add: "যোগ কৰক",
  deleteReminder: "স্মাৰক মচক",
  personalSpiritualHome: "ব্যক্তিগত আধ্যাত্মিক ঘৰ",
  completedOnDevice: "এই ডিভাইচত সম্পূৰ্ণ।",
  returnToHome: "মূল পৃষ্ঠালৈ ঘূৰি যাওক",
  pageNotFound: "উফ! পৃষ্ঠা পোৱা নগ'ল",
  backHome: "মূল পৃষ্ঠালৈ",
  beginWithMantra: "মন্ত্ৰেৰে আৰম্ভ কৰক",
  watchLiveDarshan: "লাইভ দৰ্শন চাওক",
  openLibrary: "ভাণ্ডাৰ খোলক",
  todaysPanchang: "আজিৰ পঞ্জিকা",
  dailyCalendar: "দৈনিক পঞ্জিকা",
  useMyLocation: "মোৰ অৱস্থান ব্যৱহাৰ কৰক",
  liveNow: "এতিয়া লাইভ",
  refreshLiveStatus: "লাইভ অৱস্থা সতেজ কৰক",
  sacredTextsHeritage: "পৱিত্ৰ গ্ৰন্থ আৰু হিন্দু ঐতিহ্য",
  readFullDetails: "সম্পূৰ্ণ বিৱৰণ পঢ়ক",
  priestSearch: "পুৰোহিত বিচাৰ",
  digitalJapaMala: "ডিজিটেল জপ মালা",
  reset: "ৰিছেট",
  closeFullImage: "সম্পূৰ্ণ ছবি বন্ধ",
  mantraScript: "মন্ত্ৰ লিপি",
  useRegionalScript: "মোৰ আঞ্চলিক লিপি ব্যৱহাৰ কৰক",
  explaining: "ব্যাখ্যা কৰা হৈছে…",
  listenWithContext: "প্ৰসঙ্গসহ শুনক",
  pravachanCulturalReading: "প্ৰৱচন আৰু সাংস্কৃতিক পঠন কক্ষ",
  newsletterTagline: "মাঝে মাঝে এটা চিন্তনশীল বাৰ্তা",
  newsletterDesc: "নতুন মন্ত্ৰ, পৱিত্ৰ গ্ৰন্থ সংযোজন আৰু উপযোগী উৎসৱৰ নিৰ্দেশনা—দৈনিক কোলাহল নোহোৱাকৈ।",
  emailAddressPlaceholder: "ইমেইল ঠিকনা",
  subscribeAgreement: "মই ইমেইল আপডেট পাবলৈ সন্মত। যিকোনো বাৰ্তাৰ পৰা সদস্যতা বাতিল কৰিব পাৰোঁ।",
  footerTagline: "মন্ত্ৰ সাধনা, মন্দিৰ দৰ্শন, হিন্দু পৱিত্ৰ সাহিত্য আৰু দৈনন্দিন ভক্তিমূলক শik্ষাৰ বাবে এটা শান্ত ডিজিটেল স্থান।",
  supportTheProject: "প্ৰকল্পক সমৰ্থন কৰক",
  footerDisclaimer: "শik্ষামূলক ভক্তিমূলক বিষয় · মুহূৰ্ত আৰু औपचारिक সংskarৰ বাবে যোগ্য আঞ্চলিক উৎসৰ সৈতে পৰীক্ষা কৰক।",
  heroSubtitle: "আপোনাৰ দৈনিক পৱিত্ৰ যাত্ৰাৰ বাবে এটা শান্ত স্থান।",
  heroDescription: "কালজয়ী মন্ত্ৰ শুনক, লাইভ মন্দিৰ দৰ্শন অনুভৱ কৰক, আৰু হিন্দু শাস্ত্ৰ এটা সুন্দৰ সংযুক্ত আশ্ৰয়ত অধ্যয়ন কৰক।",
  sacredWisdomLiving: "পৱিত্ৰ জ্ঞান · জীৱন্ত পৰম্পৰা",
  resources700: "700+ পৱিত্ৰ সম্পদ",
  liveTempleDiscovery: "লাইভ মন্দিৰ অন্বেষণ",
  todaysIntention: "আজিৰ সংকল্প",
  peaceInEveryBreath: "প্ৰতিটো শ্বাসত শান্তি",
  readWisdom: "জ্ঞান পঢ়ক",
  chooseSoundDarshan: "শব্দ, দৰ্শন বা শাস্ত্ৰ বাছক—প্ৰতিটো অভিজ্ঞতা সঁহাৰি দিয়ে, আপডেট হয় আৰু আপোনাৰ সৈতে চলে।",
  startListening: "শুনা আৰম্ভ কৰক",
  watchDarshan: "দৰ্শন চাওক",
  readReflect: "পঢ়ক আৰু চিন্তা কৰক",
  sacredTexts: "পৱিত্ৰ গ্ৰন্থ",
  designedAroundYou: "আপোনাৰ বাবে ডিজাইন",
  listenReadReflect: "শুনক · পঢ়ক · চিন্তা",
  fastDiscovery: "দ্ৰুত অন্বেষণ",
  sanskritAndEnglish: "সংস্কৃত আৰু ইংৰাজী",
  morningPractice: "প্ৰভাত সাধনা",
  beginWithGayatri: "Gayatri-ৰে আৰম্ভ",
  enterTheTemple: "মন্দিৰত প্ৰৱেশ",
  exploreTheGita: "Gita অন্বেষণ",
  backToDivinityHarmony: "Divinity Harmony-লৈ ঘূৰি যাওক",
  practiceRemembered: "আপোনাৰ সাধনা, সুৰক্ষিতভাৱে মনত ৰাখা হয়।",
  profileAcrossDevices: "প্ৰ'ফাইল, অৱতাৰ আৰু আধ্যাত্মিক পছন্দ ডিভাইচত সংযুক্ত ৰাখক।",
  authPoweredBy: "প্ৰমাণীকৰণ আৰু ফাইল সংৰক্ষণ Supabase-ৰ দ্বাৰা",
  authConfiguring: "একাউণ্ট সেৱা কনফিগাৰ কৰা হৈছে",
  guestAccessAvailable: "অতিথি প্ৰৱেশ উপলব্ধ। লগইন সক্ৰিয় কৰিবলৈ Supabase স্থাপনা চলাওক।",
  signInWithEmail: "আপোনাৰ একাউণ্টৰ ইমেইলেৰে ছাইন ইন কৰক।",
  email: "ইমেইল",
  password: "পাছৱৰ্ড",
  forgotPassword: "পাছৱৰ্ড পাহৰিলে?",
  createYourAccount: "আপোনাৰ একাউণ্ট সৃষ্টি কৰক",
  profileFollowsDevices: "আপোনাৰ প্ৰ'ফাইল সকলো ডিভাইচত আপোনাৰ সৈতে থাকিব।",
  minEightChars: "ন্যূনতম ৮টা আখৰ।",
  emailConfirmationNote: "আপোনাৰ Supabase প্ৰকল্পত ইমেইল নিশ্চিতকৰণৰ প্ৰয়োজন হ'ব পাৰে।",
};
