/** Complete Assamese UI pack — 225 semantic keys. */
export const asPack = {
  divinityHarmony: "দিব্য সামৰস",
  home: "মূল পৃষ্ঠা",
  mantras: "মন্ত্ৰ",
  liveDarshan: "লাইভ দৰ্শন",
  scriptures: "পৱিত্ৰ গ্ৰন্থ",
  deities: "দেৱতা",
  temples: "মন্দিৰ",
  priests: "পুৰোহিত",
  explore: "অন্বেষণ",
  login: "লগইন",
  settings: "ছেটিংছ",
  language: "ভাষা",
  english: "ইংৰাজী",
  applicationLanguage: "এপৰ ভাষা",
  elderMode: "বয়স্ক ম'ড",
  myDharma: "মোৰ ধৰ্ম",
  cultureOfIndia: "ভাৰতৰ সংস্কৃতি",
  pravachanReading: "প্ৰৱচন আৰু পঠন",
  vedicAstrology: "বৈদিক জ্যোতিষ",
  mantraLibrary: "মন্ত্ৰ ভাণ্ডাৰ",
  sacredMantras: "পৱিত্ৰ মন্ত্ৰ",
  livingDevotionalLibrary: "এটা জীৱন্ত ভক্তি ভাণ্ডাৰ",
  noMantraFound: "কোনো মন্ত্ৰ পোৱা নগ'ল। আন নাম বা দেৱতা চেষ্টা কৰক।",
  searchContactDetails: "সাম্প্ৰতিক যোগাযোগৰ বিবৰণ বিচাৰক",
  findNearMe: "মোৰ ওচৰত বিচাৰক",
  googleMaps: "গুগল মেপ",
  publicDirectory: "সৰ্বজনীন নিৰ্দেশিকা",
  todaysPractice: "আজিৰ সাধনা",
  myTraditionProfile: "মোৰ পৰম্পৰা প্ৰ'ফাইল",
  currentState: "বৰ্তমান ৰাজ্য",
  homeStateTradition: "মূল ৰাজ্য / সাংস্কৃতিক পৰম্পৰা",
  preferredLanguage: "পছন্দৰ ভাষা",
  calendarTradition: "পঞ্জিকা পৰম্পৰা",
  saveMyDharma: "মোৰ ধৰ্ম সংৰক্ষণ",
  familyRitualReminders: "পাৰিবাৰিক অনুষ্ঠানৰ স্মাৰক",
  noFamilyDatesSaved: "এতিয়ালৈ কোনো পাৰিবাৰিক তাৰিখ সংৰক্ষিত নহয়। তথ্য এই ব্ৰাউজাৰত থাকিব।",
  lightTheLamp: "দীপ জ্বলাওক",
  ganeshaInvocation: "গণেশ আবাহন",
  ishtaDevataMantra: "ইষ্টদেৱতাৰ মন্ত্ৰ",
  oneScriptureVerse: "এটা শাস্ত্ৰৰ শ্লোক",
  japaPractice: "জপ সাধনা",
  aartiClosingPrayer: "আৰতী আৰু সমাপনী প্ৰাৰ্থনা",
  observances: "অনুষ্ঠান",
  livingTraditions: "জীৱন্ত পৰম্পৰা",
  pravachanGuide: "প্ৰৱচন নিৰ্দেশিকা",
  dharmicReadingRoom: "ধাৰ্মিক পঠন কক্ষ",
  officialSources: "আধিকাৰিক উৎস",
  publisherDirect: "প্ৰকাশক-প্ৰতিচ্ছ",
  vedicAstrologyCentre: "বৈদিক জ্যোতিষ শিক্ষা কেন্দ্ৰ",
  privateBirthDetails: "ব্যক্তিগত জন্মৰ বিবৰণ",
  dateOfBirth: "জন্ম তাৰিখ",
  exactBirthTime: "সঠিক জন্ম সময়",
  birthPlace: "জন্মস্থান",
  savePrivatelyOnDevice: "এই ডিভাইচত ব্যক্তিগতভাৱে সংৰক্ষণ",
  coreCalculationVocabulary: "মূল গণনাৰ শব্দভাণ্ডাৰ",
  navagrahaStudyMap: "নৱগ্ৰহ অধ্যয়ন মানচিত্ৰ",
  searchYouTube: "YouTube-ত বিচাৰক",
  playRecording: "ৰেকৰ্ডিং চলাওক",
  devotionalAudio: "ভক্তিমূলক অডিঅ'",
  searchMantraLibrary: "মন্ত্ৰ ভাণ্ডাৰ বিচাৰক",
  all: "সকলো",
  translationLabel: "অনুবাদ:",
  explainThisMantra: "এই মন্ত্ৰটো ব্যাখ্যা কৰক",
  meaningAndContext: "অৰ্থ আৰু প্ৰসংগ:",
  favoriteMantra: "প্ৰিয় মন্ত্ৰ",
  newsletterEmail: "নিউজলেটাৰ ইমেইল",
  subscribe: "সদস্যতা",
  privacyPolicy: "গোপনীয়তা নীতি",
  termsOfUse: "ব্যৱহাৰৰ চৰ্ত",
  accessibility: "সulabhata",
  trustAndSupport: "বিশ্বাস আৰু সহায়",
  practice: "সাধনা",
  discover: "অন্বেষণ",
  yourAccount: "আপোনাৰ একাউণ্ট",
  userSettings: "ব্যৱহাৰকাৰী ছেটিংছ",
  profile: "প্ৰ'ফাইল",
  preferences: "পছন্দ",
  account: "একাউণ্ট",
  displayName: "প্ৰদৰ্শিত নাম",
  darkTheme: "গাঢ় থিম",
  loggedOut: "লগ আউট",
  loggedOutSuccess: "আপুনি সফলতাৰে লগ আউট হ'ল।",
  threeLivingPaths: "তিনিটা জীৱন্ত পথ। এটা পৱিত্ৰ স্থান।",
  yourSpiritualLibrary: "আপোনাৰ আধ্যাত্মিক ভাণ্ডাৰ",
  findWhatSpeaks: "আপোনাৰ হৃদয়ৰ সৈতে কথা পাতা বিচাৰক।",
  chooseTheMoment: "আপোনাৰ প্ৰয়োজনীয় মুহূৰ্ত বাছক।",
  sacredRhythmEveryDay: "প্ৰতিদিনৰ বাবে এটা পৱিত্ৰ তাল",
  liveTempleDarshan: "লাইভ মন্দিৰ দৰ্শন",
  welcomeBack: "পুনৰ স্বাগতম",
  createAccount: "একাউণ্ট সৃষ্টি",
  signIn: "ছাইন ইন",
  continueAsGuest: "অতিথি হিচাপে অব্যাহত ৰাখক",
  matchingPrayers: "মিলা প্ৰাৰ্থনা",
  searchMantraPlaceholder: "শিব, Krishna, শান্তি বিচাৰক…",
  exploreMantrasTemplate: "{count}+ প্ৰাৰ্থনা, বৈদিক স্তোত্ৰ আৰু মন্ত্ৰ অন্বেষণ কৰক। দেৱতা, পাঠ বা উদ্দেশ্য অনুসৰি বিচাৰক।",
  logout: "লগ আউট",
  myAccount: "মোৰ একাউণ্ট",
  signedIn: "ছাইন ইন কৰা হ'ল",
  toggleTheme: "থিম সলনি",
  devotee: "ভক্ত",
  appLanguage: "এপৰ ভাষা",
  appLanguageHint: "মেনু আৰু লেবেল সলনি কৰে। মন্ত্ৰৰ সংস্কৃত পাঠ যেনে আছে তেনেকৈ থাকে।",
  saveProfile: "প্ৰ'ফাইল সংৰক্ষণ",
  signOut: "ছাইন আউট",
  signInOrCreate: "ছাইন ইন বা একাউণ্ট সৃষ্টি",
  guestPreferences: "অতিথিৰ পছন্দ এই ব্ৰাউজাৰত থাকিব।",
  appearanceAndPlayback: "দেখা আৰু প্লেবেক",
  autoplayMedia: "মিডিয়া স্বয়ং চলাওক",
  notifications: "জ্ঞাপন",
  accountSecurity: "একাউণ্ট সুৰক্ষা",
  gotraOptional: "গোত্ৰ বা পাৰিবাৰিক পৰম্পৰা (ঐচ্ছিক)",
  yourNamePlaceholder: "আপোনাৰ নাম",
  enterIfKnown: "জানিলে মাত্ৰ লিখক",
  ishtaKulaDevata: "ইষ্ট বা কুল দেৱতা (ঐচ্ছিক)",
  chooseFamilyCalendar: "আপোনাৰ পাৰিবাৰিক পঞ্জিকা বাছক",
  signatureObservances: "প্ৰধান অনুষ্ঠান",
  traditionsAndTemples: "পৰম্পৰা আৰু মন্দিৰ",
  selectStateOrUt: "ৰাজ্য বা কেন্দ্ৰীয় অঞ্চল বাছক",
  add: "যোগ",
  deleteReminder: "স্মাৰক মচক",
  personalSpiritualHome: "ব্যক্তিগত আধ্যাত্মিক ঘৰ",
  completedOnDevice: "এই ডিভাইচত সম্পূৰ্ণ।",
  returnToHome: "মূল পৃষ্ঠালৈ ঘূৰি যাওক",
  pageNotFound: "উফ! পৃষ্ঠা পোৱা নগ'ল",
  backHome: "মূল পৃষ্ঠালৈ",
  beginWithMantra: "মন্ত্ৰেৰে আৰম্ভ",
  watchLiveDarshan: "লাইভ দৰ্শন চাওক",
  openLibrary: "ভাণ্ডাৰ খোলক",
  todaysPanchang: "আজিৰ পঞ্জিকা",
  dailyCalendar: "দৈনিক পঞ্জিকা",
  useMyLocation: "মোৰ স্থান ব্যৱহাৰ",
  liveNow: "এতিয়া লাইভ",
  refreshLiveStatus: "লাইভ স্থিতি সতেজ",
  sacredTextsHeritage: "পৱিত্ৰ গ্ৰন্থ আৰু হিন্দু ঐতিহ্য",
  readFullDetails: "সম্পূৰ্ণ বিবৰণ পঢ়ক",
  priestSearch: "পুৰোহিত বিচাৰ",
  digitalJapaMala: "ডিজিটেল জপ মালা",
  reset: "ৰিছেট",
  closeFullImage: "সম্পূৰ্ণ ছবি বন্ধ",
  mantraScript: "মন্ত্ৰ লিপি",
  useRegionalScript: "মোৰ আঞ্চলিক লিপি ব্যৱহাৰ",
  explaining: "ব্যাখ্যা কৰা হৈছে…",
  listenWithContext: "প্ৰসংগসহ শুনক",
  pravachanCulturalReading: "প্ৰৱচন আৰু সাংস্কৃতিক পঠন কক্ষ",
  newsletterTagline: "মাঝে মাঝে এটা চিন্তনশীল বাৰ্তা",
  newsletterDesc: "নতুন মন্ত্ৰ, পৱিত্ৰ গ্ৰন্থ সংযোজন আৰু উপযোগী উৎসৱৰ নিৰ্দেশনা—দৈনিক কোলাহল নোহোৱাকৈ।",
  emailAddressPlaceholder: "ইমেইল ঠিকনা",
  subscribeAgreement: "মই ইমেইল আপডেট পাবলৈ সন্মত। যিকোনো বাৰ্তাৰ পৰা সদস্যতা বাতিল কৰিব পাৰো।",
  footerTagline: "মন্ত্ৰ সাধনা, মন্দিৰ দৰ্শন, হিন্দু পৱিত্ৰ সাহিত্য আৰু দৈনন্দিন ভক্তিমূলক শিক্ষাৰ বাবে এটা শান্ত ডিজিটেল স্থান।",
  supportTheProject: "প্ৰকল্পক সমৰ্থন",
  footerDisclaimer: "শিক্ষামূলক ভক্তিমূলক বিষয় · মুহূৰ্ত আৰু औपचारिक संस्कार যোগ্য আঞ্চলিক উৎসৰ সৈতে পৰীক্ষা কৰক।",
  heroSubtitle: "আপোনাৰ দৈনন্দিন পৱিত্ৰ যাত্ৰাৰ বাবে এটা শান্ত স্থান।",
  heroDescription: "কালজয়ী মন্ত্ৰ শুনক, লাইভ মন্দিৰ দৰ্শন অনুভৱ কৰক, আৰু হিন্দু শাস্ত্ৰ এটা সুন্দৰ সংযুক্ত আশ্ৰয়ত অধ্যয়ন কৰক।",
  sacredWisdomLiving: "পৱিত্ৰ জ্ঞান · জীৱন্ত পৰম্পৰা",
  resources700: "700+ পৱিত্ৰ সম্পদ",
  liveTempleDiscovery: "লাইভ মন্দিৰ অন্বেষণ",
  todaysIntention: "আজিৰ সংকল্প",
  peaceInEveryBreath: "প্ৰতিটো শ্বাসত শান্তি",
  readWisdom: "জ্ঞান পঢ়ক",
  chooseSoundDarshan: "শব্দ, দৰ্শন বা শাস্ত্ৰ বাছক—প্ৰতিটো অভিজ্ঞতা সঁহাৰি দিয়ে, আপডেট হয় আৰু আপোনাৰ সৈতে চলে।",
  startListening: "শুনা আৰম্ভ",
  watchDarshan: "দৰ্শন চাওক",
  readReflect: "পঢ়ক আৰু চিন্তা",
  sacredTexts: "পৱিত্ৰ গ্ৰন্থ",
  designedAroundYou: "আপোনাৰ বাবে ডিজাইন",
  listenReadReflect: "শুনক · পঢ়ক · চিন্তা",
  fastDiscovery: "দ্ৰুত অন্বেষণ",
  sanskritAndEnglish: "সংস্কৃত আৰু ইংৰাজী",
  morningPractice: "প্ৰভাত সাধনা",
  beginWithGayatri: "Gayatri ৰে আৰম্ভ",
  enterTheTemple: "মন্দিৰত প্ৰৱেশ",
  exploreTheGita: "Gita অন্বেষণ",
  backToDivinityHarmony: "Divinity Harmony-লৈ ঘূৰি যাওক",
  practiceRemembered: "আপোনাৰ সাধনা, সুৰক্ষিতভাৱে মনত ৰখা হয়।",
  profileAcrossDevices: "প্ৰ'ফাইল, অৱতাৰ আৰু আধ্যাত্মিক পছন্দ ডিভাইচত সংযুক্ত ৰাখক।",
  authPoweredBy: "প্ৰমাণীকৰণ আৰু ফাইল সংৰক্ষণ Supabase-ৰ দ্বাৰা",
  authConfiguring: "একাউণ্ট সেৱা সংৰচনা হৈ আছে",
  guestAccessAvailable: "অতিথি প্ৰৱেশ উপলব্ধ। লগইন সক্ৰিয় কৰিবলৈ Supabase deployment variables যোগ কৰক।",
  signInWithEmail: "আপোনাৰ একাউণ্টত ব্যৱহৃত ইমেইলেৰে ছাইন ইন কৰক।",
  email: "ইমেইল",
  password: "পাছৱৰ্ড",
  forgotPassword: "পাছৱৰ্ড পাহৰিলে?",
  createYourAccount: "আপোনাৰ একাউণ্ট সৃষ্টি",
  profileFollowsDevices: "আপোনাৰ প্ৰ'ফাইল সকলো ডিভাইচত আপোনাৰ সৈতে থাকিব।",
  minEightChars: "ন্যূনতম ৮ আখৰ।",
  emailConfirmationNote: "আপোনাৰ Supabase project-ৰ দ্বাৰা ইমেইল নিশ্চিতকৰণ প্ৰয়োজন হ'ব পাৰে।",
  listenAndChant: "শুনক আৰু জপ কৰক",
  templeBroadcasts: "মন্দিৰ সম্প্ৰচাৰ",
  readSanskritJapa: "সংস্কৃত পঢ়ক, অৰ্থ বুজি দৈনিক জপ অব্যাহত ৰাখক।",
  enterTempleStreams: "স্বয়ংক্ৰিয়ভাৱে আৱিষ্কৃত আৰু নবীকৰণ হোৱা মন্দিৰ ষ্ট্ৰিমত প্ৰৱেশ কৰক।",
  exploreVedasHeritage: "Vedas, Gitas, Puranas, দৰ্শন, বংশ আৰু হিন্দু ঐতিহ্য অন্বেষণ কৰক।",
  checkingLive: "লাইভ পৰীক্ষা হৈ আছে",
  liveNowLower: "এতিয়া লাইভ",
  streamsFound: "ষ্ট্ৰিম পোৱা গ'ল",
  mantrasMetric: "মন্ত্ৰ",
  worksMetric: "ৰচনা",
  moveNaturally: "শব্দ, পৱিত্ৰ চিত্ৰ, অৰ্থ আৰু মূল পাঠৰ মাজত স্বাভাৱিকভাৱে ঘূৰি থাকক। প্ৰতিটো পথ ম'বাইল আৰু ডেস্কটপত শান্ত আৰু সঁহাৰি দিয়া থাকে।",
  searchHundredsResources: "শত শত সম্পদ বিচাৰক।",
  originalTextContext: "মূল পাঠ আৰু স্পষ্ট প্ৰসংগ।",
  noNoiseMenus: "কোনো কোলাহল নাই, জটিল মেনু নাই—শুনা, দৰ্শন আৰু শাশ্বত জ্ঞানৰ পোনপটীয়া পথ।",
  gayatriDetail: "স্পষ্টতা আৰু জাগৰণৰ বাবে এটা উজ্জ্বল বৈদিক প্ৰাৰ্থনা।",
  discoverDarshanStreams: "বৰ্তমান সম্প্ৰচাৰিত দৰ্শন ষ্ট্ৰিম বিচাৰক।",
  gitaReadingDetail: "শান্ত পঠন দৃশ্যৰ সৈতে উৎস-সমৰ্থিত অধ্যায় খোলক।",
  carryPractice: "সাধনা আপোনাৰ সৈতে ৰাখক।",
  loadingTodayDetails: "আজিৰ বিৱৰণ ল'ড হৈ আছে…",
  panchangLocalized: "স্থানীয় পঞ্জিকা",
  nakshatra: "Nakshatra",
  tithi: "Tithi",
  yoga: "Yoga",
  karana: "Karana",
  starOf27: "২৭ৰ ভিতৰত {n} নম্বৰ তৰা",
  sunMoonCombination: "সূৰ্য–চন্দ্ৰ সংযোগ",
  halfTithiDivision: "অৰ্ধ-তিথি বিভাজন",
  sunrise: "সূৰ্যোদয়",
  sunset: "সূৰ্যাস্ত",
  moon: "চন্দ্ৰ",
  locationNotSupported: "এই ব্ৰাউজাৰে অৱস্থান সমৰ্থন নকৰে।",
  locationPermissionDenied: "অৱস্থানৰ অনুমতি দিয়া হোৱা নাই। ভাৰতৰ অৱলোকন দেখুওৱা হৈছে।",
  panchangCalendarAlt: "সূৰ্য, চন্দ্ৰ আৰু নক্ষত্ৰৰ জ্যোতিৰ্বিদ্যা পঞ্জিকা",
  templePriestDirectory: "মন্দিৰ আৰু পুৰোহিত নিৰ্দেশিকা",
  pleaseConfirmSubscribe: "অনুগ্ৰহ কৰি নিশ্চিত কৰক যে আপুনি ইমেইল আপডেট পাব বিচাৰে।",
  alreadySubscribed: "আপুনি ইতিমধ্যে সদস্য।",
  welcomeSubscribed: "স্বাগত—আপোনাৰ সদস্যতা নিশ্চিত হ'ল।",
  pleaseTryAgain: "অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।",
  liveLabel: "লাইভ",
};
