/** Complete Bengali UI pack — 186 semantic keys. */
export const bnPack = {
  divinityHarmony: "দিব্য সামরস",
  home: "প্রধান পাতা",
  mantras: "মন্ত্র",
  liveDarshan: "লাইভ দর্শন",
  scriptures: "পবিত্র গ্রন্থ",
  deities: "দেবতা",
  temples: "মন্দির",
  priests: "পুরোহিত",
  explore: "অন্বেষণ",
  login: "লগইন",
  settings: "সেটিংস",
  language: "ভাষা",
  english: "ইংরেজি",
  applicationLanguage: "অ্যাপের ভাষা",
  elderMode: "বয়স্ক মোড",
  myDharma: "আমার ধর্ম",
  cultureOfIndia: "ভারতের সংস্কৃতি",
  pravachanReading: "প্রবচন ও পাঠ",
  vedicAstrology: "বৈদিক জ্যোতিষ",
  mantraLibrary: "মন্ত্র ভাণ্ডার",
  sacredMantras: "পবিত্র মন্ত্র",
  livingDevotionalLibrary: "একটি জীবন্ত ভক্তি ভাণ্ডার",
  noMantraFound: "কোনো মন্ত্র পাওয়া যায়নি। অন্য নাম বা দেবতা চেষ্টা করুন।",
  searchContactDetails: "বর্তমান যোগাযোগের বিবরণ খুঁজুন",
  findNearMe: "আমার কাছে খুঁজুন",
  googleMaps: "গুগল ম্যাপস",
  publicDirectory: "সর্বজনীন নির্দেশিকা",
  todaysPractice: "আজকের সাধনা",
  myTraditionProfile: "আমার পরম্পরা প্রোফাইল",
  currentState: "বর্তমান রাজ্য",
  homeStateTradition: "নিজ রাজ্য / সাংস্কৃতিক পরম্পরা",
  preferredLanguage: "পছন্দের ভাষা",
  calendarTradition: "পঞ্জিকা পরম্পরা",
  saveMyDharma: "আমার ধর্ম সংরক্ষণ",
  familyRitualReminders: "পারিবারিক অনুষ্ঠানের অনুস্মারক",
  noFamilyDatesSaved: "এখনও কোনো পারিবারিক তারিখ সংরক্ষিত নেই। তথ্য এই ব্রাউজারে থাকবে।",
  lightTheLamp: "প্রদীপ জ্বালান",
  ganeshaInvocation: "গণেশ আবাহন",
  ishtaDevataMantra: "ইষ্টদেবতার মন্ত্র",
  oneScriptureVerse: "একটি শাস্ত্রের শ্লোক",
  japaPractice: "জপ সাধনা",
  aartiClosingPrayer: "আরati ও সমাপনী প্রার্থনা",
  observances: "অনুষ্ঠান",
  livingTraditions: "জীবন্ত পরম্পরা",
  pravachanGuide: "প্রবচন নির্দেশিকা",
  dharmicReadingRoom: "ধarmic পাঠকক্ষ",
  officialSources: "আধিকারিক উৎস",
  publisherDirect: "প্রকাশক-সরাসরি",
  vedicAstrologyCentre: "বৈদিক জ্যোতিষ শিক্ষা কেন্দ্র",
  privateBirthDetails: "ব্যক্তিগত জন্মের বিবরণ",
  dateOfBirth: "জন্ম তারিখ",
  exactBirthTime: "সঠিক জন্ম সময়",
  birthPlace: "জন্মস্থান",
  savePrivatelyOnDevice: "এই ডিভাইসে ব্যক্তিগতভাবে সংরক্ষণ",
  coreCalculationVocabulary: "মূল গণনার শব্দভাণ্ডার",
  navagrahaStudyMap: "নবগ্রহ অধ্যয়ন মানচিত্র",
  searchYouTube: "YouTube-এ খুঁজুন",
  playRecording: "রেকording চালান",
  devotionalAudio: "ভক্তিমূলক অডিও",
  searchMantraLibrary: "মন্ত্র ভাণ্ডার খুঁজুন",
  all: "সব",
  translationLabel: "অনুবাদ:",
  explainThisMantra: "এই মন্ত্রটি ব্যাখ্যা করুন",
  meaningAndContext: "অর্থ ও প্রসঙ্গ:",
  favoriteMantra: "প্রিয় মন্ত্র",
  newsletterEmail: "নিউজলেটার ইমেল",
  subscribe: "সাবস্ক্রাইব",
  privacyPolicy: "গোপনীয়তা নীতি",
  termsOfUse: "ব্যবহারের শর্ত",
  accessibility: "অ্যাক্সেসিবিলিটি",
  trustAndSupport: "বিশ্বাস ও সহায়তা",
  practice: "সাধনা",
  discover: "অন্বেষণ",
  yourAccount: "আপনার অ্যাকাউন্ট",
  userSettings: "ব্যবহারকারী সেটিংস",
  profile: "প্রোফাইল",
  preferences: "পছন্দ",
  account: "অ্যাকাউন্ট",
  displayName: "প্রদর্শিত নাম",
  darkTheme: "গাঢ় থিম",
  loggedOut: "লগ আউট হয়েছে",
  loggedOutSuccess: "আপনি সফলভাবে লগ আউট হয়েছেন।",
  threeLivingPaths: "তিনটি জীবন্ত পথ। একটি পবিত্র স্থান।",
  yourSpiritualLibrary: "আপনার আধ্যাত্মিক ভাণ্ডার",
  findWhatSpeaks: "যা আপনার হৃদয়ে কথা বলে তা খুঁজুন।",
  chooseTheMoment: "আপনার প্রয়োজনীয় মুহূর্ত বেছে নিন।",
  sacredRhythmEveryDay: "প্রতিদিনের জন্য একটি পবিত্র ছন্দ",
  liveTempleDarshan: "লাইভ মন্দির দর্শন",
  welcomeBack: "আবার স্বাগতম",
  createAccount: "অ্যাকাউন্ট তৈরি",
  signIn: "সাইন ইন",
  continueAsGuest: "অতিথি হিসেবে চালিয়ে যান",
  matchingPrayers: "মিলে যাওয়া প্রার্থনা",
  searchMantraPlaceholder: "শিব, Krishna, শান্তি খুঁজুন…",
  exploreMantrasTemplate: "{count}+ প্রার্থনা, বৈদিক স্তোত্র ও মন্ত্র অন্বেষণ করুন। দেবতা, পাঠ বা উদ্দেশ্য অনুযায়ী খুঁজুন।",
  logout: "লগ আউট",
  myAccount: "আমার অ্যাকাউন্ট",
  signedIn: "সাইন ইন করা",
  toggleTheme: "থিম পরিবর্তন",
  devotee: "ভক্ত",
  appLanguage: "অ্যাপের ভাষা",
  appLanguageHint: "মেনু ও লেবেল পরিবর্তন করে। মন্ত্রের সংস্কৃত পাঠ যেমন আছে তেমনই থাকে।",
  saveProfile: "প্রোফাইল সংরক্ষণ",
  signOut: "সাইন আউট",
  signInOrCreate: "সাইন ইন বা অ্যাকাউন্ট তৈরি",
  guestPreferences: "অতিথির পছন্দ এই ব্রাউজারে থাকবে।",
  appearanceAndPlayback: "দেখার ধরন ও প্লেব্যাক",
  autoplayMedia: "মিডিয়া স্বয়ংক্রিয় চালান",
  notifications: "বিজ্ঞপ্তি",
  accountSecurity: "অ্যাকাউন্ট নিরাপত্তা",
  gotraOptional: "গোত্র বা পারিবারিক পরম্পরা (ঐচ্ছিক)",
  yourNamePlaceholder: "আপনার নাম",
  enterIfKnown: "জানলে তবেই লিখুন",
  ishtaKulaDevata: "ইষ্ট বা কুল দেবতা (ঐচ্ছিক)",
  chooseFamilyCalendar: "আপনার পারিবারিক পঞ্জিকা বেছে নিন",
  signatureObservances: "প্রধান অনুষ্ঠান",
  traditionsAndTemples: "পরম্পরা ও মন্দির",
  selectStateOrUt: "রাজ্য বা কেন্দ্রশাসিত অঞ্চল নির্বাচন",
  add: "যোগ",
  deleteReminder: "অনুস্মারক মুছুন",
  personalSpiritualHome: "ব্যক্তিগত আধ্যাত্মিক ঘর",
  completedOnDevice: "এই ডিভাইসে সম্পন্ন।",
  returnToHome: "প্রধান পাতায় ফিরুন",
  pageNotFound: "উফ! পাতা পাওয়া যায়নি",
  backHome: "প্রধান পাতায়",
  beginWithMantra: "মন্ত্র দিয়ে শুরু",
  watchLiveDarshan: "লাইভ দর্শন দেখুন",
  openLibrary: "ভাণ্ডার খুলুন",
  todaysPanchang: "আজকের পঞ্জিকা",
  dailyCalendar: "দৈনিক পঞ্জিকা",
  useMyLocation: "আমার অবস্থান ব্যবহার",
  liveNow: "এখন লাইভ",
  refreshLiveStatus: "লাইভ অবস্থা রিফ্রেশ",
  sacredTextsHeritage: "পবিত্র গ্রন্থ ও হিন্দু ঐতিহ্য",
  readFullDetails: "সম্পূর্ণ বিবরণ পড়ুন",
  priestSearch: "পুরোহিত খোঁজ",
  digitalJapaMala: "ডিজিটাল জপ মালা",
  reset: "রিসেট",
  closeFullImage: "পূর্ণ ছবি বন্ধ",
  mantraScript: "মন্ত্র লিপি",
  useRegionalScript: "আমার আঞ্চলিক লিপি ব্যবহার",
  explaining: "ব্যাখ্যা করা হচ্ছে…",
  listenWithContext: "প্রসঙ্গসহ শুনুন",
  pravachanCulturalReading: "প্রবচন ও সাংস্কৃতিক পাঠকক্ষ",
  newsletterTagline: "মাঝে মাঝে একটি চিন্তাশীল বার্তা",
  newsletterDesc: "নতুন মন্ত্র, পবিত্র গ্রন্থ সংযোজন ও উপযোগী উৎসব নির্দেশনা—দৈনিক শব্দহল্লা ছাড়াই।",
  emailAddressPlaceholder: "ইমেল ঠিকানা",
  subscribeAgreement: "আমি ইমেল আপডেট পেতে সম্মত। যেকোনো বার্তা থেকে সদস্যতা বাতিল করতে পারি।",
  footerTagline: "মন্ত্র সাধনা, মন্দির দর্শন, হিন্দু পবিত্র সাহিত্য ও দৈনন্দিন ভক্তিমূলক শিক্ষার জন্য একটি শান্ত ডিজিটাল স্থান।",
  supportTheProject: "প্রকল্পকে সমর্থন",
  footerDisclaimer: "শিক্ষামূলক ভক্তিমূলক বিষয় · মুহূর্ত ও औपचारिक संस्कার যোগ্য আঞ্চলিক উৎস দিয়ে যাচাই করুন।",
  heroSubtitle: "আপনার দৈনিক পবিত্র যাত্রার জন্য একটি শান্ত স্থান।",
  heroDescription: "কালজয়ী মন্ত্র শুনুন, লাইভ মন্দির দর্শন অনুভব করুন, এবং হিন্দু শাস্ত্র এক সুন্দর সংযুক্ত আশ্রয়ে অধ্যয়ন করুন।",
  sacredWisdomLiving: "পবিত্র জ্ঞান · জীবন্ত পরম্পরা",
  resources700: "700+ পবিত্র সম্পদ",
  liveTempleDiscovery: "লাইভ মন্দির অন্বেষণ",
  todaysIntention: "আজকের সংকল্প",
  peaceInEveryBreath: "প্রতিটি শ্বাসে শান্তি",
  readWisdom: "জ্ঞান পড়ুন",
  chooseSoundDarshan: "শব্দ, দর্শন বা শাস্ত্র বেছে নিন—প্রতিটি অভিজ্ঞতা প্রতিক্রিয়া, আপডেট ও আপনার সঙ্গে চলে।",
  startListening: "শোনা শুরু",
  watchDarshan: "দর্শন দেখুন",
  readReflect: "পড়ুন ও চিন্তা",
  sacredTexts: "পবিত্র গ্রন্থ",
  designedAroundYou: "আপনার জন্য ডিজাইন",
  listenReadReflect: "শুনুন · পড়ুন · চিন্তা",
  fastDiscovery: "দ্রুত অন্বেষণ",
  sanskritAndEnglish: "সংস্কৃত ও ইংরেজি",
  morningPractice: "প্রভাত সাধনা",
  beginWithGayatri: "Gayatri দিয়ে শুরু",
  enterTheTemple: "মন্দিরে প্রবেশ",
  exploreTheGita: "Gita অন্বেষণ",
  backToDivinityHarmony: "Divinity Harmony-তে ফিরুন",
  practiceRemembered: "আপনার সাধনা, নিরাপদে মনে রাখা হয়।",
  profileAcrossDevices: "প্রোফাইল, অবতার ও আধ্যাত্মিক পছন্দ ডিভাইসে সংযুক্ত রাখুন।",
  authPoweredBy: "প্রমাণীকরণ ও ফাইল সংরক্ষণ Supabase দ্বারা",
  authConfiguring: "অ্যাকাউন্ট সেবা কনফিগার করা হচ্ছে",
  guestAccessAvailable: "অতিথি প্রবেশ উপলব্ধ। লগইন সক্রিয় করতে Supabase স্থাপনা চল চালু করুন।",
  signInWithEmail: "আপনার অ্যাকাউন্টের ইমেল দিয়ে সাইন ইন করুন।",
  email: "ইমেল",
  password: "পাসওয়ার্ড",
  forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
  createYourAccount: "আপনার অ্যাকাউন্ট তৈরি",
  profileFollowsDevices: "আপনার প্রোফাইল সব ডিভাইসে আপনার সঙ্গে থাকবে।",
  minEightChars: "সর্বনিম্ন ৮ অক্ষর।",
  emailConfirmationNote: "আপনার Supabase প্রকল্পে ইমেল নিশ্চয়তা প্রয়োজন হতে পারে।",
};
