/** Complete Gujarati UI pack — 225 semantic keys. */
export const guPack = {
  divinityHarmony: "દિવ્ય સામરસ",
  home: "મુખ્ય પૃષ્ઠ",
  mantras: "મંત્ર",
  liveDarshan: "લાઇવ દર્શન",
  scriptures: "પવિત્ર ગ્રંથ",
  deities: "દેવતાઓ",
  temples: "મંદિર",
  priests: "પુરોહિત",
  explore: "શોધ",
  login: "લૉગિન",
  settings: "સેટિંગ્સ",
  language: "ભાષા",
  english: "અંગ્રેજી",
  applicationLanguage: "એપની ભાષા",
  elderMode: "વૃદ્ધ મોડ",
  myDharma: "મારો ધર્મ",
  cultureOfIndia: "ભારતની સંસ્કૃતિ",
  pravachanReading: "પ્રવચન અને વાંચન",
  vedicAstrology: "વૈદિક જ્યોતિષ",
  mantraLibrary: "મંત્ર ગ્રંથાલય",
  sacredMantras: "પવિત્ર મંત્ર",
  livingDevotionalLibrary: "જીવંત ભક્તિ ગ્રંથાલય",
  noMantraFound: "કોઈ મંત્ર મળ્યો નહીં. બીજું નામ અથવા દેવતા અજમાવો.",
  searchContactDetails: "વર્તમાન સંપર્ક વિગતો શોધો",
  findNearMe: "મારી નજીક શોધો",
  googleMaps: "ગૂગલ મેપ્સ",
  publicDirectory: "જાહેર નિર્દેશિકા",
  todaysPractice: "આજની સાધના",
  myTraditionProfile: "મારી પરંપરા પ્રોફાઇલ",
  currentState: "વર્તમાન રાજ્ય",
  homeStateTradition: "મૂળ રાજ્ય / સાંસ્કૃતિક પરંપરા",
  preferredLanguage: "પસંદગીની ભાષા",
  calendarTradition: "પંચાંગ પરંપરા",
  saveMyDharma: "મારો ધર્મ સાચવો",
  familyRitualReminders: "કુટુંબીય વિધિ સ્મારક",
  noFamilyDatesSaved: "હજુ સુધી કોઈ કુટુંબીય તારીખ સાચવેલ નથી. ડેટા આ બ્રાઉઝરમાં રહેશે.",
  lightTheLamp: "દીવો પ્રજ્વલિત કરો",
  ganeshaInvocation: "ગણેશ આવાહન",
  ishtaDevataMantra: "ઇષ્ટદેવતા મંત્ર",
  oneScriptureVerse: "એક શાસ્ત્ર શ્લોક",
  japaPractice: "જપ સાધના",
  aartiClosingPrayer: "આરતી અને સમાપન પ્રાર્થના",
  observances: "વિધિઓ",
  livingTraditions: "જીવંત પરંપરાઓ",
  pravachanGuide: "પ્રવચન માર્ગદર્શિકા",
  dharmicReadingRoom: "ધાર્મિક વાંચન કક્ષ",
  officialSources: "અધિકૃત સ્રોતો",
  publisherDirect: "પ્રકાશક-સીધા",
  vedicAstrologyCentre: "વૈદિક જ્યોતિષ શિક્ષણ કેન્દ્ર",
  privateBirthDetails: "ખાનગી જન્મ વિગતો",
  dateOfBirth: "જન્મ તારીખ",
  exactBirthTime: "ચોક્કસ જન્મ સમય",
  birthPlace: "જન્મ સ્થળ",
  savePrivatelyOnDevice: "આ ઉપકરણ પર ખાનગી રીતે સાચવો",
  coreCalculationVocabulary: "મૂળ ગણતરી શબ્દભંડોળ",
  navagrahaStudyMap: "નવગ્રહ અભ્યાસ નકશો",
  searchYouTube: "YouTube પર શોધો",
  playRecording: "ધ્વનિમુદ્રણ ચલાવો",
  devotionalAudio: "ભક્તિ ઑડિયો",
  searchMantraLibrary: "મંત્ર ગ્રંથાલય શોધો",
  all: "બધા",
  translationLabel: "અનુવાદ:",
  explainThisMantra: "આ મંત્ર સમજાવો",
  meaningAndContext: "અર્થ અને સંદર્ભ:",
  favoriteMantra: "મનપસંદ મંત્ર",
  newsletterEmail: "ન્યૂઝલેટર ઇમેઇલ",
  subscribe: "સબ્સ્ક્રાઇબ",
  privacyPolicy: "ગોપનીયતા નીતિ",
  termsOfUse: "ઉપયોગની શરતો",
  accessibility: "સુલભતા",
  trustAndSupport: "વિશ્વાસ અને સહાય",
  practice: "સાધના",
  discover: "શોધ",
  yourAccount: "તમારું ખાતું",
  userSettings: "વપરાશકર્તા સેટિંગ્સ",
  profile: "પ્રોફાઇલ",
  preferences: "પસંદગીઓ",
  account: "ખાતું",
  displayName: "પ્રદર્શિત નામ",
  darkTheme: "ઘાટું થીમ",
  loggedOut: "લૉગ આઉટ",
  loggedOutSuccess: "તમે સફળતાપૂર્વક લૉગ આઉટ થયા.",
  threeLivingPaths: "ત્રણ જીવંત માર્ગ. એક પવિત્ર સ્થાન.",
  yourSpiritualLibrary: "તમારું આધ્યાત્મિક ગ્રંથાલય",
  findWhatSpeaks: "તમારા હૃદય સાથે બોલે તે શોધો.",
  chooseTheMoment: "તમને જોઈતો ક્ષણ પસંદ કરો.",
  sacredRhythmEveryDay: "દરરોજ માટે પવિત્ર તાલ",
  liveTempleDarshan: "લાઇવ મંદિર દર્શન",
  welcomeBack: "પાછા સ્વાગત",
  createAccount: "ખાતું બનાવો",
  signIn: "સાઇન ઇન",
  continueAsGuest: "મહેમાન તરીકે ચાલુ રાખો",
  matchingPrayers: "મળતા મંત્ર",
  searchMantraPlaceholder: "શિવ, Krishna, શાંતિ શોધો…",
  exploreMantrasTemplate: "{count}+ પ્રાર્થનાઓ, વેદ સ્તોત્ર અને મંત્ર શોધો. દેવતા, પાઠ અથવા હેતુ અનુસાર શોધો.",
  logout: "લૉગ આઉટ",
  myAccount: "મારું ખાતું",
  signedIn: "સાઇન ઇન થયા",
  toggleTheme: "થીમ બદલો",
  devotee: "ભક્ત",
  appLanguage: "એપની ભાષા",
  appLanguageHint: "મેનુ અને લેબલ બદલે છે. મંત્રનો સંસ્કૃત પાઠ જેમ છે તેમ રહે.",
  saveProfile: "પ્રોફાઇલ સાચવો",
  signOut: "સાઇન આઉટ",
  signInOrCreate: "સાઇન ઇન કરો અથવા ખાતું બનાવો",
  guestPreferences: "મહેમાન પસંદગીઓ આ બ્રાઉઝરમાં રહેશે.",
  appearanceAndPlayback: "દેખાવ અને પ્લેબેક",
  autoplayMedia: "મીડિયા આપમેળે ચલાવો",
  notifications: "સૂચનાઓ",
  accountSecurity: "ખાતું સુરક્ષા",
  gotraOptional: "ગોત્ર અથવા કુટુંબ પરંપરા (વૈકલ્પિક)",
  yourNamePlaceholder: "તમારું નામ",
  enterIfKnown: "જાણ હોય તો જ દાખલ કરો",
  ishtaKulaDevata: "ઇષ્ટ અથવા કુળ દેવતા (વૈકલ્પિક)",
  chooseFamilyCalendar: "તમારું કુટુંબ પંચાંગ પસંદ કરો",
  signatureObservances: "મુખ્ય વિધિઓ",
  traditionsAndTemples: "પરંપરાઓ અને મંદિરો",
  selectStateOrUt: "રાજ્ય અથવા કેન્દ્રશાસિત પ્રદેશ પસંદ કરો",
  add: "ઉમેરો",
  deleteReminder: "સ્મારક કાઢી નાખો",
  personalSpiritualHome: "વ્યક્તિગત આધ્યાત્મિક ઘર",
  completedOnDevice: "આ ઉપકરણ પર પૂર્ણ.",
  returnToHome: "મુખ્ય પૃષ્ઠ પર પાછા",
  pageNotFound: "અરે! પૃષ્ઠ મળ્યું નહીં",
  backHome: "મુખ્ય પૃષ્ઠ",
  beginWithMantra: "મંત્રથી શરૂઆત",
  watchLiveDarshan: "લાઇવ દર્શન જુઓ",
  openLibrary: "ગ્રંથાલય ખોલો",
  todaysPanchang: "આજનું પંચાંગ",
  dailyCalendar: "દૈનિક પંચાંગ",
  useMyLocation: "મારું સ્થાન વાપરો",
  liveNow: "હમણાં લાઇવ",
  refreshLiveStatus: "લાઇવ સ્થિતિ તાજી કરો",
  sacredTextsHeritage: "પવિત્ર ગ્રંથ અને હિંદુ વારસો",
  readFullDetails: "સંપૂર્ણ વિગતો વાંચો",
  priestSearch: "પુરોહિત શોધ",
  digitalJapaMala: "ડિજિટલ જપ માળા",
  reset: "રીસેટ",
  closeFullImage: "પૂર્ણ ચિત્ર બંધ",
  mantraScript: "મંત્ર લિપિ",
  useRegionalScript: "મારી પ્રાદેશિક લિપિ વાપરો",
  explaining: "સમજાવી રહ્યા છીએ…",
  listenWithContext: "સંદર્ભ સાથે સાંભળો",
  pravachanCulturalReading: "પ્રવચન અને સાંસ્કૃતિક વાંચન કક્ષ",
  newsletterTagline: "ક્યારેક ક્યારેક વિચારશીલ સંદેશ",
  newsletterDesc: "નવા મંત્ર, પવિત્ર ગ્રંથ ઉમેરો અને ઉપયોગી તહેવાર માર્ગદર્શન—દૈનિક ઘોંઘાટ વિના.",
  emailAddressPlaceholder: "ઇમેઇલ સરનામું",
  subscribeAgreement: "હું ઇમેઇલ અપડેટ્સ મેળવવા સહમત છું. કોઈ પણ સંદેશમાંથી સબ્સ્ક્રિપ્શન રદ કરી શકું.",
  footerTagline: "મંત્ર સાધના, મંદિર દર્શન, હિંદુ પવિત્ર સાહિત્ય અને રોજિંદી ભક્તિ શિક્ષણ માટે શાંત ડિજિટલ સ્થાન.",
  supportTheProject: "પ્રોજેક્ટને સમર્થન",
  footerDisclaimer: "શૈક્ષણિક ભક્તિ સામગ્રી · મુહૂર્ત અને ઔપચારિક સંસ્કાર યોગ્ય પ્રાદેશિક સ્રોતથી ચકાસો.",
  heroSubtitle: "તમારી દૈનિક પવિત્ર યાત્રા માટે શાંત સ્થાન.",
  heroDescription: "કાલજયી મંત્ર સાંભળો, લાઇવ મંદિર દર્શન અનુભવો, અને હિંદુ શાસ્ત્રોનો અભ્યાસ એક સુંદર જોડાયેલ આશ્રયમાં કરો.",
  sacredWisdomLiving: "પવિત્ર જ્ઞાન · જીવંત પરંપરા",
  resources700: "700+ પવિત્ર સંસાધનો",
  liveTempleDiscovery: "લાઇવ મંદિર શોધ",
  todaysIntention: "આજનો સંકલ્પ",
  peaceInEveryBreath: "દર શ્વાસમાં શાંતિ",
  readWisdom: "જ્ઞાન વાંચો",
  chooseSoundDarshan: "ધ્વનિ, દર્શન અથવા શાસ્ત્ર પસંદ કરો—દરેક અનુભવ પ્રતિસાદ આપે, અપડેટ થાય અને તમારી સાથે ચાલે.",
  startListening: "સાંભળવાનું શરૂ કરો",
  watchDarshan: "દર્શન જુઓ",
  readReflect: "વાંચો અને ચિંતન",
  sacredTexts: "પવિત્ર ગ્રંથ",
  designedAroundYou: "તમારા માટે ડિઝાઇન",
  listenReadReflect: "સાંભળો · વાંચો · ચિંતન",
  fastDiscovery: "ઝડપી શોધ",
  sanskritAndEnglish: "સંસ્કૃત અને અંગ્રેજી",
  morningPractice: "સવારની સાધના",
  beginWithGayatri: "Gayatri થી શરૂઆત",
  enterTheTemple: "મંદિરમાં પ્રવેશ",
  exploreTheGita: "Gita શોધો",
  backToDivinityHarmony: "Divinity Harmony પર પાછા",
  practiceRemembered: "તમારી સાધના, સુરક્ષિત રીતે યાદ રાખવામાં આવે.",
  profileAcrossDevices: "તમારી પ્રોફાઇલ, અવતાર અને આધ્યાત્મિક પસંદગીઓ ઉપકરણોમાં જોડાયેલી રાખો.",
  authPoweredBy: "પ્રમાણીકરણ અને ફાઇલ સંગ્રહ Supabase દ્વારા",
  authConfiguring: "ખાતું સેવા કન્ફિગર થઈ રહી છે",
  guestAccessAvailable: "મહેમાન પ્રવેશ ઉપલબ્ધ. લૉગિન સક્રિય કરવા Supabase ડિપ્લોયમેન્ટ ચલ ઉમેરો.",
  signInWithEmail: "તમારા ખાતા માટે વપરાયેલ ઇમેઇલથી સાઇન ઇન કરો.",
  email: "ઇમેઇલ",
  password: "પાસવર્ડ",
  forgotPassword: "પાસવર્ડ ભૂલી ગયા?",
  createYourAccount: "તમારું ખાતું બનાવો",
  profileFollowsDevices: "તમારી પ્રોફાઇલ બધા ઉપકરણોમાં તમારી સાથે રહેશે.",
  minEightChars: "ઓછામાં ઓછા 8 અક્ષરો.",
  emailConfirmationNote: "તમારા Supabase પ્રોજેક્ટ દ્વારા ઇમેઇલ પુષ્ટિ જરૂરી હોઈ શકે.",
  listenAndChant: "સાંભળો અને જપ કરો",
  templeBroadcasts: "મંદિર પ્રસારણ",
  readSanskritJapa: "સંસ્કૃત વાંચો, અર્થ સમજો અને તમારો દૈનિક જપ ચાલુ રાખો.",
  enterTempleStreams: "સ્વચાલિત રીતે શોધાયેલ અને તાજા થતા મંદિર સ્ટ્રીમમાં પ્રવેશ કરો.",
  exploreVedasHeritage: "Vedas, Gitas, Puranas, દર્શન, વંશ અને હિંદુ વારસો શોધો.",
  checkingLive: "લાઇવ તપાસ થઈ રહી છે",
  liveNowLower: "હમણાં લાઇવ",
  streamsFound: "સ્ટ્રીમ મળી",
  mantrasMetric: "મંત્ર",
  worksMetric: "રચનાઓ",
  moveNaturally: "ધ્વનિ, પવિત્ર ચિત્ર, અર્થ અને મૂળ પાઠ વચ્ચે કુદરતી રીતે ફરો. દરેક માર્ગ મોબાઇલ અને ડેસ્કટૉપ પર શાંત અને પ્રતિસાદી રહે છે.",
  searchHundredsResources: "સેંકડો સંસાધનો શોધો.",
  originalTextContext: "મૂળ પાઠ અને સ્પષ્ટ સંદર્ભ.",
  noNoiseMenus: "કોઈ ઘોંઘાટ નહીં, કોઈ જટિલ મેનુ નહીં—સાંભળવા, દર્શન અને શાશ્વત જ્ઞાનનો સીધો માર્ગ.",
  gayatriDetail: "સ્પષ્ટતા અને જાગૃતિ માટે એક ઉજ્જ્વળ વૈદિક પ્રાર્થના.",
  discoverDarshanStreams: "હાલમાં પ્રસારિત થતા દર્શન સ્ટ્રીમ શોધો.",
  gitaReadingDetail: "શાંત વાંચન દૃશ્ય સાથે સ્રોત-સમર્થિત અધ્યાય ખોલો.",
  carryPractice: "સાધના તમારી સાથે રાખો.",
  loadingTodayDetails: "આજના વિગતો લોડ થઈ રહ્યા છે…",
  panchangLocalized: "સ્થાનિક પંચાંગ",
  nakshatra: "Nakshatra",
  tithi: "Tithi",
  yoga: "Yoga",
  karana: "Karana",
  starOf27: "27 માંથી {n} નક્ષત્ર",
  sunMoonCombination: "સૂર્ય–ચંદ્ર સંયોગ",
  halfTithiDivision: "અર્ધ-તિથિ વિભાગ",
  sunrise: "સૂર્યોદય",
  sunset: "સૂર્યાસ્ત",
  moon: "ચંદ્ર",
  locationNotSupported: "આ બ્રાઉઝર સ્થાનને સપોર્ટ કરતું નથી.",
  locationPermissionDenied: "સ્થાનની પરવાનગી મળી નથી. ભારતનું અવલોકન બતાવવામાં આવે છે.",
  panchangCalendarAlt: "સૂર્ય, ચંદ્ર અને નક્ષત્ર ખગોળીય પંચાંગ",
  templePriestDirectory: "મંદિર અને પુરોહિત નિર્દેશિકા",
  pleaseConfirmSubscribe: "કૃપા કરીને ખાતરી કરો કે તમે ઇમેઇલ અપડેટ્સ મેળવવા માંગો છો.",
  alreadySubscribed: "તમે પહેલેથી જ સબ્સ્ક્રાઇબ છો.",
  welcomeSubscribed: "સ્વાગત છે—તમારી સબ્સ્ક્રિપ્શનની પુષ્ટિ થઈ ગઈ.",
  pleaseTryAgain: "કૃપા કરીને ફરી પ્રયાસ કરો.",
  liveLabel: "લાઇવ",
};
