/** Complete Malayalam UI pack — 225 semantic keys. */
export const mlPack = {
  divinityHarmony: "ദിവ്യ സാമരസ്യം",
  home: "മുഖ്യ പേജ്",
  mantras: "മന്ത്രങ്ങൾ",
  liveDarshan: "ലൈവ് ദർശനം",
  scriptures: "പവിത്ര ഗ്രന്ഥങ്ങൾ",
  deities: "ദേവതകൾ",
  temples: "ക്ഷേത്രങ്ങൾ",
  priests: "പുരോഹിതർ",
  explore: "പര്യവേക്ഷണം",
  login: "ലോഗിൻ",
  settings: "ക്രമീകരണങ്ങൾ",
  language: "ഭാഷ",
  english: "ഇംഗ്ലീഷ്",
  applicationLanguage: "ആപ്പ് ഭാഷ",
  elderMode: "മുതിർന്നവർ മോഡ്",
  myDharma: "എന്റെ ധർമ്മം",
  cultureOfIndia: "ഇന്ത്യയുടെ സംസ്കാരം",
  pravachanReading: "പ്രവചനവും വായനയും",
  vedicAstrology: "വേദ ജ്യോതിഷം",
  mantraLibrary: "മന്ത്ര ലൈബ്രറി",
  sacredMantras: "പവിത്ര മന്ത്രങ്ങൾ",
  livingDevotionalLibrary: "ജീവന്ത ഭക്തി ലൈബ്രറി",
  noMantraFound: "മന്ത്രം കണ്ടെത്തിയില്ല. മറ്റൊരു പേരോ ദേവതയോ ശ്രമിക്കുക.",
  searchContactDetails: "നിലവിലെ ബന്ധപ്പെടൽ വിവരങ്ങൾ തിരയുക",
  findNearMe: "എന്റെ അടുത്ത് തിരയുക",
  googleMaps: "ഗൂഗിൾ മാപ്പ്",
  publicDirectory: "പൊതു ഡയറക്ടറി",
  todaysPractice: "ഇന്നത്തെ പരിശീലനം",
  myTraditionProfile: "എന്റെ പാരമ്പര്യ പ്രൊഫൈൽ",
  currentState: "നിലവിലെ സംസ്ഥാനം",
  homeStateTradition: "സ്വദേശ സംസ്ഥാനം / സാംസ്കാരിക പാരമ്പര്യം",
  preferredLanguage: "ഇഷ്ടപ്പെട്ട ഭാഷ",
  calendarTradition: "കലണ്ടർ പാരമ്പര്യം",
  saveMyDharma: "എന്റെ ധർമ്മം സേവ് ചെയ്യുക",
  familyRitualReminders: "കുടുംബ ചടങ്ങ് ഓർമ്മപ്പെടുത്തലുകൾ",
  noFamilyDatesSaved: "കുടുംബ തീയതികൾ ഇതുവരെ സേവ് ചെയ്തിട്ടില്ല. ഡാറ്റ ഈ ബ്രൗസറിൽ തുടരും.",
  lightTheLamp: "വിളക്ക് കത്തിക്കുക",
  ganeshaInvocation: "ഗണേശ ആഹ്വാനം",
  ishtaDevataMantra: "ഇഷ്ടദേവതാ മന്ത്രം",
  oneScriptureVerse: "ഒരു ശാസ്ത്ര ശ്ലോകം",
  japaPractice: "ജപ പരിശീലനം",
  aartiClosingPrayer: "ആരത്തിയും അവസാന പ്രാർത്ഥനയും",
  observances: "ചടങ്ങുകൾ",
  livingTraditions: "ജീവന്ത പാരമ്പര്യങ്ങൾ",
  pravachanGuide: "പ്രവചന ഗൈഡ്",
  dharmicReadingRoom: "ധാർമിക വായനാ മുറി",
  officialSources: "ഔദ്യോഗിക ഉറവിടങ്ങൾ",
  publisherDirect: "പ്രസാധകൻ-നേരിട്ട്",
  vedicAstrologyCentre: "വേദ ജ്യോതിഷ പഠന കേന്ദ്രം",
  privateBirthDetails: "സ്വകാര്യ ജനന വിവരങ്ങൾ",
  dateOfBirth: "ജനന തീയതി",
  exactBirthTime: "കൃത്യമായ ജനന സമയം",
  birthPlace: "ജനന സ്ഥലം",
  savePrivatelyOnDevice: "ഈ ഉപകരണത്തിൽ സ്വകാര്യമായി സേവ് ചെയ്യുക",
  coreCalculationVocabulary: "അടിസ്ഥാന കണക്കുകൂട്ടൽ പദാവലി",
  navagrahaStudyMap: "നവഗ്രഹ പഠന മാപ്പ്",
  searchYouTube: "YouTube-ൽ തിരയുക",
  playRecording: "റെക്കോർഡിംഗ് പ്ലേ ചെയ്യുക",
  devotionalAudio: "ഭക്തി ഓഡിയോ",
  searchMantraLibrary: "മന്ത്ര ലൈബ്രറി തിരയുക",
  all: "എല്ലാം",
  translationLabel: "വിവർത്തനം:",
  explainThisMantra: "ഈ മന്ത്രം വിശദീകരിക്കുക",
  meaningAndContext: "അർത്ഥവും സന്ദർഭവും:",
  favoriteMantra: "ഇഷ്ട മന്ത്രം",
  newsletterEmail: "ന്യൂസ്‌ലെറ്റർ ഇമെയിൽ",
  subscribe: "സബ്‌സ്‌ക്രൈബ്",
  privacyPolicy: "സ്വകാര്യതാ നയം",
  termsOfUse: "ഉപയോഗ നിബന്ധനകൾ",
  accessibility: "പ്രവേശനക്ഷമത",
  trustAndSupport: "വിശ്വാസവും പിന്തുണയും",
  practice: "പരിശീലനം",
  discover: "പര്യവേക്ഷണം",
  yourAccount: "നിങ്ങളുടെ അക്കൗണ്ട്",
  userSettings: "ഉപയോക്താ ക്രമീകരണങ്ങൾ",
  profile: "പ്രൊഫൈൽ",
  preferences: "മുൻഗണനകൾ",
  account: "അക്കൗണ്ട്",
  displayName: "പ്രദർശന പേര്",
  darkTheme: "ഇരുണ്ട തീം",
  loggedOut: "ലോഗ് ഔട്ട്",
  loggedOutSuccess: "നിങ്ങൾ വിജയകരമായി ലോഗ് ഔട്ട് ചെയ്തു.",
  threeLivingPaths: "മൂന്ന് ജീവന്ത പാതകൾ. ഒരു പവിത്ര സ്ഥലം.",
  yourSpiritualLibrary: "നിങ്ങളുടെ ആത്മീയ ലൈബ്രറി",
  findWhatSpeaks: "നിങ്ങളുടെ ഹൃദയവുമായി സംസാരിക്കുന്നത് കണ്ടെത്തുക.",
  chooseTheMoment: "നിങ്ങൾക്ക് ആവശ്യമുള്ള നിമിഷം തിരഞ്ഞെടുക്കുക.",
  sacredRhythmEveryDay: "എല്ലാ ദിവസവും ഒരു പവിത്ര താളം",
  liveTempleDarshan: "ലൈവ് ക്ഷേത്ര ദർശനം",
  welcomeBack: "വീണ്ടും സ്വാഗതം",
  createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
  signIn: "സൈൻ ഇൻ",
  continueAsGuest: "അതിഥിയായി തുടരുക",
  matchingPrayers: "പൊരുത്തപ്പെടുന്ന പ്രാർത്ഥനകൾ",
  searchMantraPlaceholder: "ശിവൻ, Krishna, ശാന്തി…",
  exploreMantrasTemplate: "{count}+ പ്രാർത്ഥനകൾ, വേദ സ്തോത്രങ്ങൾ, മന്ത്രങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക. ദേവത, പാഠം അല്ലെങ്കിൽ ഉദ്ദേശ്യം അനുസരിച്ച് തിരയുക.",
  logout: "ലോഗ് ഔട്ട്",
  myAccount: "എന്റെ അക്കൗണ്ട്",
  signedIn: "സൈൻ ഇൻ ചെയ്തു",
  toggleTheme: "തീം മാറ്റുക",
  devotee: "ഭക്തൻ",
  appLanguage: "ആപ്പ് ഭാഷ",
  appLanguageHint: "മെനുകളും ലേബലുകളും മാറ്റുന്നു. മന്ത്ര സംസ്കൃത പാഠം എഴുതിയതുപോലെ തുടരും.",
  saveProfile: "പ്രൊഫൈൽ സേവ്",
  signOut: "സൈൻ ഔട്ട്",
  signInOrCreate: "സൈൻ ഇൻ ചെയ്യുക അല്ലെങ്കിൽ അക്കൗണ്ട് സൃഷ്ടിക്കുക",
  guestPreferences: "അതിഥി മുൻഗണനകൾ ഈ ബ്രൗസറിൽ തുടരും.",
  appearanceAndPlayback: "ദൃശ്യവും പ്ലേബാക്കും",
  autoplayMedia: "മീഡിയ ഓട്ടോപ്ലേ",
  notifications: "അറിയിപ്പുകൾ",
  accountSecurity: "അക്കൗണ്ട് സുരക്ഷ",
  gotraOptional: "ഗോത്രം അല്ലെങ്കിൽ കുടുംബ പാരമ്പര്യം (ഓപ്ഷണൽ)",
  yourNamePlaceholder: "നിങ്ങളുടെ പേര്",
  enterIfKnown: "അറിയാമെങ്കിൽ മാത്രം നൽകുക",
  ishtaKulaDevata: "ഇഷ്ട അല്ലെങ്കിൽ കുല ദേവത (ഓപ്ഷണൽ)",
  chooseFamilyCalendar: "നിങ്ങളുടെ കുടുംബ കലണ്ടർ തിരഞ്ഞെടുക്കുക",
  signatureObservances: "പ്രധാന ചടങ്ങുകൾ",
  traditionsAndTemples: "പാരമ്പര്യങ്ങളും ക്ഷേത്രങ്ങളും",
  selectStateOrUt: "സംസ്ഥാനം അല്ലെങ്കിൽ UT തിരഞ്ഞെടുക്കുക",
  add: "ചേർക്കുക",
  deleteReminder: "ഓർമ്മപ്പെടുത്തൽ ഇല്ലാതാക്കുക",
  personalSpiritualHome: "വ്യക്തിഗത ആത്മീയ ആവാസം",
  completedOnDevice: "ഈ ഉപകരണത്തിൽ പൂർത്തിയായി.",
  returnToHome: "മുഖ്യ പേജിലേക്ക് മടങ്ങുക",
  pageNotFound: "അയ്യോ! പേജ് കണ്ടെത്തിയില്ല",
  backHome: "മുഖ്യ പേജിലേക്ക്",
  beginWithMantra: "മന്ത്രത്തോടെ ആരംഭിക്കുക",
  watchLiveDarshan: "ലൈവ് ദർശനം കാണുക",
  openLibrary: "ലൈബ്രറി തുറക്കുക",
  todaysPanchang: "ഇന്നത്തെ പഞ്ചാംഗം",
  dailyCalendar: "ദൈനിക കലണ്ടർ",
  useMyLocation: "എന്റെ സ്ഥാനം ഉപയോഗിക്കുക",
  liveNow: "ഇപ്പോൾ ലൈവ്",
  refreshLiveStatus: "ലൈവ് നില പുതുക്കുക",
  sacredTextsHeritage: "പവിത്ര ഗ്രന്ഥങ്ങളും ഹിന്ദു പൈതൃകവും",
  readFullDetails: "പൂർണ്ണ വിവരങ്ങൾ വായിക്കുക",
  priestSearch: "പുരോഹിത തിരയൽ",
  digitalJapaMala: "ഡിജിറ്റൽ ജപ മാല",
  reset: "റീസെറ്റ്",
  closeFullImage: "പൂർണ്ണ ചിത്രം അടയ്ക്കുക",
  mantraScript: "മന്ത്ര ലിപി",
  useRegionalScript: "എന്റെ പ്രാദേശിക ലിപി ഉപയോഗിക്കുക",
  explaining: "വിശദീകരിക്കുന്നു…",
  listenWithContext: "സന്ദർഭത്തോടെ കേൾക്കുക",
  pravachanCulturalReading: "പ്രവചന & സാംസ്കാരിക വായനാ മുറി",
  newsletterTagline: "എപ്പോഴെങ്കിലും ഒരു ചിന്താപൂർവ്വ സന്ദേശം",
  newsletterDesc: "പുതിയ മന്ത്രങ്ങൾ, പവിത്ര ഗ്രന്ഥ സേർപ്പുകൾ, ഉപയോഗപ്രദമായ ഉത്സവ മാർഗദർശനം—ദൈനംദിന ശബ്ദമില്ലാതെ.",
  emailAddressPlaceholder: "ഇമെയിൽ വിലാസം",
  subscribeAgreement: "ഇമെയിൽ അപ്‌ഡേറ്റുകൾ സ്വീകരിക്കാൻ ഞാൻ സമ്മതിക്കുന്നു. ഏത് സന്ദേശത്തിലും നിന്ന് സബ്സ്ക്രിപ്ഷൻ റദ്ദാക്കാം.",
  footerTagline: "മന്ത്ര പരിശീലനം, ക്ഷേത്ര ദർശനം, ഹിന്ദു പവിത്ര സാഹിത്യം, ദൈനംദിന ഭക്തി പഠനം എന്നിവയ്ക്കുള്ള ശാന്തമായ ഡിജിറ്റൽ ഇടം.",
  supportTheProject: "പ്രോജക്റ്റിനെ പിന്തുണയ്ക്കുക",
  footerDisclaimer: "വിദ്യാഭ്യാസ ഭക്തി ഉള്ളടക്കം · മുഹൂർത്തവും ഔപചാരിക സംസ്കാരം യോഗ്യമായ പ്രാദേശിക ഉറവിടം ഉപയോഗിച്ച് പരിശോധിക്കുക.",
  heroSubtitle: "നിങ്ങളുടെ ദൈനംദിന പവിത്ര യാത്രയ്ക്ക് ഒരു ശാന്തമായ ഇടം.",
  heroDescription: "കാലാതീത മന്ത്രങ്ങൾ കേൾക്കുക, ലൈവ് ക്ഷേത്ര ദർശനം അനുഭവിക്കുക, ഹിന്ദു ശാസ്ത്രങ്ങൾ ഒരു മനോഹരമായി ബന്ധിപ്പിച്ച ആശ്രയത്തിൽ അധ്യയനം ചെയ്യുക.",
  sacredWisdomLiving: "പവിത്ര ജ്ഞാനം · ജീവന്ത പാരമ്പര്യം",
  resources700: "700+ പവിത്ര ഉപാധികൾ",
  liveTempleDiscovery: "ലൈവ് ക്ഷേത്ര കണ്ടെത്തൽ",
  todaysIntention: "ഇന്നത്തെ സങ്കൽപ്പം",
  peaceInEveryBreath: "ഓരോ ശ്വാസത്തിലും ശാന്തി",
  readWisdom: "ജ്ഞാനം വായിക്കുക",
  chooseSoundDarshan: "ശബ്ദം, ദർശനം അല്ലെങ്കിൽ ശാസ്ത്രം തിരഞ്ഞെടുക്കുക—ഓരോ അനുഭവവും പ്രതികരിക്കുന്നു, പുതുക്കുന്നു, നിങ്ങളോടൊപ്പം നീങ്ങുന്നു.",
  startListening: "കേൾക്കാൻ തുടങ്ങുക",
  watchDarshan: "ദർശനം കാണുക",
  readReflect: "വായിച്ച് ചിന്തിക്കുക",
  sacredTexts: "പവിത്ര ഗ്രന്ഥങ്ങൾ",
  designedAroundYou: "നിങ്ങൾക്കായി രൂപകൽപ്പന",
  listenReadReflect: "കേൾ · വായ · ചിന്ത",
  fastDiscovery: "വേഗത്തിലുള്ള കണ്ടെത്തൽ",
  sanskritAndEnglish: "സംസ്കൃതവും ഇംഗ്ലീഷും",
  morningPractice: "രാവിലെ പരിശീലനം",
  beginWithGayatri: "Gayatri-യോടെ ആരംഭിക്കുക",
  enterTheTemple: "ക്ഷേത്രത്തിൽ പ്രവേശിക്കുക",
  exploreTheGita: "Gita പര്യവേക്ഷണം ചെയ്യുക",
  backToDivinityHarmony: "Divinity Harmony-ലേക്ക് മടങ്ങുക",
  practiceRemembered: "നിങ്ങളുടെ പരിശീലനം, സുരക്ഷിതമായി ഓർമ്മിച്ചിരിക്കുന്നു.",
  profileAcrossDevices: "നിങ്ങളുടെ പ്രൊഫൈൽ, അവതാർ, ആത്മീയ മുൻഗണനകൾ ഉപകരണങ്ങളിൽ ബന്ധിപ്പിച്ച് സൂക്ഷിക്കുക.",
  authPoweredBy: "പ്രാമാണീകരണവും ഫയൽ സംഭരണവും Supabase-ൽ നിന്ന്",
  authConfiguring: "അക്കൗണ്ട് സേവ കോൺഫിഗർ ചെയ്യുന്നു",
  guestAccessAvailable: "അതിഥി പ്രവേശനം ലഭ്യമാണ്. ലോഗിൻ പ്രവർത്തനക്ഷമമാക്കാൻ Supabase ഡിപ്ലോയ്‌മെന്റ് ചരങ്ങൾ ചേർക്കുക.",
  signInWithEmail: "അക്കൗണ്ടിൽ ഉപയോഗിച്ച ഇമെയിൽ ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക.",
  email: "ഇമെയിൽ",
  password: "പാസ്‌വേഡ്",
  forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
  createYourAccount: "നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക",
  profileFollowsDevices: "നിങ്ങളുടെ പ്രൊഫൈൽ എല്ലാ ഉപകരണങ്ങളിലും നിങ്ങളോടൊപ്പം ഉണ്ടാകും.",
  minEightChars: "കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ.",
  emailConfirmationNote: "Supabase പ്രോജക്റ്റ് ഇമെയിൽ സ്ഥിരീകരണം ആവശ്യമാകാം.",
  listenAndChant: "കേൾക്കുകയും ജപം ചെയ്യുകയും ചെയ്യുക",
  templeBroadcasts: "ക്ഷേത്ര പ്രക്ഷേപണങ്ങൾ",
  readSanskritJapa: "സംസ്കൃതം വായിച്ച് അർത്ഥം മനസ്സിലാക്കി ദൈനംദിന ജപം തുടരുക.",
  enterTempleStreams: "സ്വയം കണ്ടെത്തി പുതുക്കപ്പെടുന്ന ക്ഷേത്ര സ്ട്രീമുകളിലേക്ക് പ്രവേശിക്കുക.",
  exploreVedasHeritage: "Vedas, Gitas, Puranas, തത്വം, വംശാവലി, ഹിന്ദു പൈതൃകം എന്നിവ അന്വേഷിക്കുക.",
  checkingLive: "ലൈവ് പരിശോധിക്കുന്നു",
  liveNowLower: "ഇപ്പോൾ ലൈവ്",
  streamsFound: "സ്ട്രീമുകൾ കണ്ടെത്തി",
  mantrasMetric: "മന്ത്രങ്ങൾ",
  worksMetric: "രചനകൾ",
  moveNaturally: "ശബ്ദം, പവിത്ര ചിത്രം, അർത്ഥം, മൂലപാഠം എന്നിവയ്ക്കിടയിൽ സ്വാഭാവികമായി സഞ്ചരിക്കുക. ഓരോ പാതയും മൊബൈലിലും ഡെസ്ക്ടോപ്പിലും ശാന്തവും പ്രതികരിക്കുന്നതുമായിരിക്കും.",
  searchHundredsResources: "നൂറുകണക്കിന് ഉറവിടങ്ങൾ തിരയുക.",
  originalTextContext: "മൂലപാഠവും വ്യക്തമായ സന്ദർഭവും.",
  noNoiseMenus: "ശബ്ദമില്ല, സങ്കീർണ്ണ മെനുകളില്ല—കേൾക്കൽ, ദർശനം, ശാശ്വത ജ്ഞാനം എന്നിവയിലേക്ക് നേരിട്ടുള്ള പാത.",
  gayatriDetail: "വ്യക്തതയ്ക്കും ഉണരവിനും ഒരു തിളങ്ങുന്ന വൈദിക പ്രാർത്ഥന.",
  discoverDarshanStreams: "ഇപ്പോൾ പ്രക്ഷേപണം ചെയ്യുന്ന ദർശന സ്ട്രീമുകൾ കണ്ടെത്തുക.",
  gitaReadingDetail: "ശാന്തമായ വായനാ ദൃശ്യത്തോടെ ഉറവിട-പിന്തുണയുള്ള അധ്യായങ്ങൾ തുറക്കുക.",
  carryPractice: "സാധന നിങ്ങളോടൊപ്പം കൊണ്ടുപോകുക.",
  loadingTodayDetails: "ഇന്നത്തെ വിവരങ്ങൾ ലോഡ് ചെയ്യുന്നു…",
  panchangLocalized: "പ്രാദേശിക പഞ്ചാംഗം",
  nakshatra: "Nakshatra",
  tithi: "Tithi",
  yoga: "Yoga",
  karana: "Karana",
  starOf27: "27-ൽ {n} നക്ഷത്രം",
  sunMoonCombination: "സൂര്യ–ചന്ദ്ര സംയോഗം",
  halfTithiDivision: "അർദ്ധ-തിഥി വിഭാഗം",
  sunrise: "സൂര്യോദയം",
  sunset: "സൂര്യാസ്തമയം",
  moon: "ചന്ദ്രൻ",
  locationNotSupported: "ഈ ബ്രൗസർ ലൊക്കേഷൻ പിന്തുണയ്ക്കുന്നില്ല.",
  locationPermissionDenied: "ലൊക്കേഷൻ അനുമതി നൽകിയില്ല. ഇന്ത്യയുടെ അവലോകനം കാണിക്കുന്നു.",
  panchangCalendarAlt: "സൂര്യൻ, ചന്ദ്രൻ, നക്ഷത്രം എന്നിവയുടെ ജ്യോതിർഗണിത പഞ്ചാംഗം",
  templePriestDirectory: "ക്ഷേത്രവും പുരോഹിത നിര്ദേശികදും",
  pleaseConfirmSubscribe: "ഇമെയിൽ അപ്‌ഡേറ്റുകൾ സ്വീകരിക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുവെന്ന് ദയവായി സ്ഥിരീകരിക്കുക.",
  alreadySubscribed: "നിങ്ങൾ ഇതിനകം സബ്‌സ്‌ക്രൈബ് ചെയ്തിട്ടുണ്ട്.",
  welcomeSubscribed: "സ്വാഗതം—നിങ്ങളുടെ സബ്‌സ്‌ക്രിപ്‌ഷൻ സ്ഥിരീകരിച്ചു.",
  pleaseTryAgain: "ദയവായി വീണ്ടും ശ്രമിക്കുക.",
  liveLabel: "ലൈവ്",
};
