/** Keys 95–186 tail sections in native script (from kn/hi extra templates). */

export const teExtra = {
  myAccount: "నా ఖాతా",
  signedIn: "సైన్ ఇన్ అయ్యారు",
  toggleTheme: "థీమ్ మార్చండి",
  devotee: "భక్తుడు",
  appLanguage: "యాప్ భాష",
  appLanguageHint:
    "మెనూలు మరియు లేబుల్‌లు మారుతాయి. మంత్ర సంస్కృత పాఠం రాసినట్లుగా ఉంటుంది.",
  saveProfile: "ప్రొఫైల్ సేవ్ చేయండి",
  signOut: "సైన్ అవుట్",
  signInOrCreate: "సైన్ ఇన్ లేదా ఖాతా సృష్టించండి",
  guestPreferences: "అతిథి అభిరుచులు ఈ బ్రౌజర్‌లో ఉంటాయి.",
  appearanceAndPlayback: "రూపం మరియు ప్లేబ్యాక్",
  autoplayMedia: "మీడియా ఆటోప్లే",
  notifications: "నోటిఫికేషన్‌లు",
  accountSecurity: "ఖాతా భద్రత",
  gotraOptional: "గోత్రం లేదా కుటుంబ సంప్రదాయం (ఐచ్ఛికం)",
  yourNamePlaceholder: "మీ పేరు",
  enterIfKnown: "తెలిస్తే మాత్రమే నమోదు చేయండి",
  ishtaKulaDevata: "ఇష్ట లేదా కుల దేవత (ఐచ్ఛికం)",
  chooseFamilyCalendar: "మీ కుటుంబ పంచాంగం ఎంచుకోండి",
  signatureObservances: "ప్రధాన విధులు",
  traditionsAndTemples: "సంప్రదాయాలు మరియు దేవాలయాలు",
  selectStateOrUt: "రాష్ట్రం లేదా UT ఎంచుకోండి",
  add: "జోడించండి",
  deleteReminder: "గుర్తు తొలగించండి",
  personalSpiritualHome: "వ్యక్తిగత ఆధ్యాత్మిక గృహం",
  completedOnDevice: "ఈ పరికరంలో పూర్తయింది.",
  returnToHome: "ముఖ్య పేజీకి తిరిగి",
  pageNotFound: "అయ్యో! పేజీ కనుగొనబడలేదు",
  backHome: "ముఖ్య పేజీకి",
  beginWithMantra: "మంత్రంతో ప్రారంభించండి",
  watchLiveDarshan: "లైవ్ దర్శనం చూడండి",
  openLibrary: "గ్రంథాలయం తెరవండి",
  todaysPanchang: "నేటి పంచాంగం",
  dailyCalendar: "దైనిక పంచాంగం",
  useMyLocation: "నా స్థానం వాడండి",
  liveNow: "ఇప్పుడు లైవ్",
  refreshLiveStatus: "లైవ్ స్థితి రిఫ్రెష్",
  sacredTextsHeritage: "పవిత్ర గ్రంథాలు మరియు హిందూ వారసత్వం",
  readFullDetails: "పూర్తి వివరాలు చదవండి",
  priestSearch: "పురోహిత శోధ",
  digitalJapaMala: "డిజిటల్ జప మాల",
  reset: "రీసెట్",
  closeFullImage: "పూర్తి చిత్రం మూసివేయండి",
  mantraScript: "మంత్ర లిపి",
  useRegionalScript: "నా ప్రాంతీయ లిపి వాడండి",
  explaining: "వివరిస్తున్నాం…",
  listenWithContext: "సందర్భంతో వినండి",
  pravachanCulturalReading: "ప్రవచన మరియు సాంస్కృతిక చదవడం గది",
  newsletterTagline: "అప్పుడappudu oka aalochanapoorvaka sandesam",
  newsletterDesc:
    "కొత్త మంత్రాలు, పవిత్ర గ్రంథ జోడింపులు మరియు ఉపయోగకరమైన పండుగ మార్గదర్శకత్వం—రోజువారీ గందరగోళం లేకుండా.",
  emailAddressPlaceholder: "ఇమెయిల్ చిరునామా",
  subscribeAgreement:
    "ఇమెయిల్ అప్‌డేట్‌లు స్వీకరించడానికి అంగీకరిస్తున్నాను. ఏ సందేశam నుండైనా చందా రద్దు చేయవచ్చు.",
  footerTagline:
    "మంత్ర సాధన, దేవాలయ దర్శనం, హిందూ పవిత్ర సాహిత్యం మరియు రోజువారీ భక్తి అభ్యాసానికి ప్రశాంత డిజిటల్ స్థలం.",
  supportTheProject: "ప్రాజెక్ట్‌కు మద్దతు",
  footerDisclaimer:
    "విద్యా భక్తి విషయం · ముహూర్తం మరియు औपchārik saṃskār-లను అర్హ ప్రాంతీయ మూలంతో ధృవీకరించండi.",
  heroSubtitle: "మీ రోజువారీ పవిత్ర ప్రయాణam కోసం ప్రశాంత స్థలం.",
  heroDescription:
    "కాలatmika మంత్రాలు వినండి, లైవ్ దేవాలయ దర్శనam అనుభవించండi, హిందూ scriptures ఒక అందమైన connected sanctuaryలో చదవండi.",
  sacredWisdomLiving: "పవిత్ర jñāna · జీవant సంప్రదాయం",
  resources700: "700+ పవిత్ర resources",
  liveTempleDiscovery: "లైవ్ దేవాలయ discovery",
  todaysIntention: "నేటి సankalpa",
  peaceInEveryBreath: "ప్రతి శ్వాసlo శanti",
  readWisdom: "jñāna చదవండి",
  chooseSoundDarshan:
    "ధ్వani, darshan లేదా scripture ఎంచukondi—prati anubhavam respond avutundi, update avutundi mariyu mee tho velutundi.",
  startListening: "వినడం ప్రారంభించండి",
  watchDarshan: "దర్శనం చూడండి",
  readReflect: "చదవandi alochinchandi",
  sacredTexts: "పవిత్ర గ్రంథాలు",
  designedAroundYou: "mee kosam design",
  listenReadReflect: "vinandi · chadivandi · alochinchandi",
  fastDiscovery: "vega discovery",
  sanskritAndEnglish: "sanskrutamu mariyu inglish",
  morningPractice: "udayam sadhana",
  beginWithGayatri: "Gayatri tho prarambhinchandi",
  enterTheTemple: "devaalayamlo praveshinchandi",
  exploreTheGita: "Gita anveshinchandi",
  backToDivinityHarmony: "Divinity Harmony ki tirigi",
  practiceRemembered: "mee sadhana, surakshitamga gurtunchabadutundi.",
  profileAcrossDevices:
    "mee profile, avatar mariyu aadhyatmika preferences devices lo connect chesi unchandi.",
  authPoweredBy: "pramanikaranam mariyu file storage Supabase dwara",
  authConfiguring: "khaataa seva configure avutondi",
  guestAccessAvailable:
    "atithi access available. login enable cheyadaniki Supabase deployment variables add cheyandi.",
  signInWithEmail: "mee khaataa kosam upayoginchina email tho sign in cheyandi.",
  email: "email",
  password: "password",
  forgotPassword: "password marchipoyara?",
  createYourAccount: "mee khaataa srushtinchandi",
  profileFollowsDevices: "mee profile anni devices lo mee tho untundi.",
  minEightChars: "minimum 8 aksharalu.",
  emailConfirmationNote: "mee Supabase project dwara email confirmation avasaram avachu.",
};
