/** Complete Tamil UI pack — 225 semantic keys. */
export const taPack = {
  divinityHarmony: "திவ்ய சாமரசம்",
  home: "முகப்பு",
  mantras: "மந்திரங்கள்",
  liveDarshan: "நேரடி தர்சனம்",
  scriptures: "புனித நூல்கள்",
  deities: "தெய்வங்கள்",
  temples: "கோயில்கள்",
  priests: "புரோகிதர்கள்",
  explore: "ஆராயுங்கள்",
  login: "உள்நுழை",
  settings: "அமைப்புகள்",
  language: "மொழி",
  english: "ஆங்கிலம்",
  applicationLanguage: "பயன்பாட்டு மொழி",
  elderMode: "முதியோர் பயன்முறை",
  myDharma: "என் தர்மம்",
  cultureOfIndia: "இந்தியாவின் கலாச்சாரம்",
  pravachanReading: "பிரவசனம் & வாசிப்பு",
  vedicAstrology: "வேத ஜோதிடம்",
  mantraLibrary: "மந்திர நூலகம்",
  sacredMantras: "புனித மந்திரங்கள்",
  livingDevotionalLibrary: "உயிரோட்டமான பக்தி நூலகம்",
  noMantraFound: "மந்திரம் கிடைக்கவில்லை. வேறு பெயர் அல்லது தெய்வத்தை முயற்சிக்கவும்.",
  searchContactDetails: "தற்போதைய தொடர்பு விவரங்களைத் தேடுங்கள்",
  findNearMe: "என் அருகில் தேடுங்கள்",
  googleMaps: "கூகுள் வரைபடம்",
  publicDirectory: "பொது அடைவு",
  todaysPractice: "இன்றைய பயிற்சி",
  myTraditionProfile: "என் பாரம்பரிய சுயவிவரம்",
  currentState: "தற்போதைய மாநிலம்",
  homeStateTradition: "தாய்நாடு / கலாச்சார பாரம்பரியம்",
  preferredLanguage: "விருப்ப மொழி",
  calendarTradition: "நாள்காட்டி பாரம்பரியம்",
  saveMyDharma: "என் தர்மம் சேமிக்க",
  familyRitualReminders: "குடும்ப சடங்கு நினைவூட்டல்கள்",
  noFamilyDatesSaved: "குடும்ப தேதிகள் இன்னும் சேமிக்கப்படவில்லை. தரவு இந்த உலாவியில் இருக்கும்.",
  lightTheLamp: "விளக்கேற்றுங்கள்",
  ganeshaInvocation: "வinēyaka அழைப்பு",
  ishtaDevataMantra: "இஷ்ட தெய்வ மந்திரம்",
  oneScriptureVerse: "ஒரு சாஸ்திர வசனம்",
  japaPractice: "ஜப பயிற்சி",
  aartiClosingPrayer: "ஆரத்தி மற்றும் முடிவு பிரார்த்தனை",
  observances: "சடங்குகள்",
  livingTraditions: "உயிருள்ள பாரம்பரியங்கள்",
  pravachanGuide: "பிரவசன வழிகாட்டி",
  dharmicReadingRoom: "தarmic வாசிப்பு அறை",
  officialSources: "அதிகாரப்பூர்வ ஆதாரங்கள்",
  publisherDirect: "வெளியீட்டாளர் நேரடி",
  vedicAstrologyCentre: "வேத ஜோதிட கற்றல் மையம்",
  privateBirthDetails: "தனிப்பட்ட பிறப்பு விவரங்கள்",
  dateOfBirth: "பிறந்த தேதி",
  exactBirthTime: "துல்லியமான பிறப்பு நேரம்",
  birthPlace: "பிறந்த இடம்",
  savePrivatelyOnDevice: "இந்த சாதனத்தில் தனிப்பட்ட முறையில் சேமிக்க",
  coreCalculationVocabulary: "அடிப்படை கணக்கீட்டு சொற்கள்",
  navagrahaStudyMap: "நவக்கிரக படிப்பு வரைபடம்",
  searchYouTube: "YouTube தேடுங்கள்",
  playRecording: "பதிவை இயக்குங்கள்",
  devotionalAudio: "பக்தி ஒலி",
  searchMantraLibrary: "மந்திர நூலகத்தைத் தேடுங்கள்",
  all: "அனைத்தும்",
  translationLabel: "மொழிபெயர்ப்பு:",
  explainThisMantra: "இந்த மந்திரத்தை விளக்குங்கள்",
  meaningAndContext: "பொருள் மற்றும் சூழல்:",
  favoriteMantra: "பிடித்த மந்திரம்",
  newsletterEmail: "செய்திமடல் மின்னஞ்சல்",
  subscribe: "சந்தா",
  privacyPolicy: "தனியுரிமைக் கொள்கை",
  termsOfUse: "பயன்பாட்டு விதிமுறைகள்",
  accessibility: "அணுகல்தன்மை",
  trustAndSupport: "நம்பிக்கை & ஆதரவு",
  practice: "பயிற்சி",
  discover: "ஆராயுங்கள்",
  yourAccount: "உங்கள் கணக்கு",
  userSettings: "பயனர் அமைப்புகள்",
  profile: "சுயவிவரம்",
  preferences: "விருப்பத்தேர்வுகள்",
  account: "கணக்கு",
  displayName: "காட்சி பெயர்",
  darkTheme: "இருண்ட தீம்",
  loggedOut: "வெளியேறியது",
  loggedOutSuccess: "நீங்கள் வெற்றிகரமாக வெளியேறினீர்கள்.",
  threeLivingPaths: "மூன்று உயிருள்ள பாதைகள். ஒரு புனித இடம்.",
  yourSpiritualLibrary: "உங்கள் ஆன்மீக நூலகம்",
  findWhatSpeaks: "உங்கள் இதயத்துடன் பேசுவதைக் கண்டறியுங்கள்.",
  chooseTheMoment: "உங்களுக்குத் தேவையான தருணத்தைத் தேர்ந்தெடுங்கள்.",
  sacredRhythmEveryDay: "ஒவ்வொரு நாளுக்கும் புனித தாளம்",
  liveTempleDarshan: "நேரடி கோயில் தர்சனம்",
  welcomeBack: "மீண்டும் வரவேற்கிறோம்",
  createAccount: "கணக்கு உருவாக்கு",
  signIn: "உள்நுழை",
  continueAsGuest: "விருந்தினராக தொடரவும்",
  matchingPrayers: "பொருந்தும் பிரார்த்தனைகள்",
  searchMantraPlaceholder: "சிவன், Krishna, அமைதி தேடுங்கள்…",
  exploreMantrasTemplate: "{count}+ பிரார்த்தனைகள், வேத ஸ்தோத்திரங்கள் மற்றும் மந்திரங்களை ஆராயுங்கள். தெய்வம், பாடம் அல்லது நோக்கத்தால் தேடுங்கள்.",
  logout: "வெளியேறு",
  myAccount: "என் கணக்கு",
  signedIn: "உள்நுழைந்துள்ளீர்கள்",
  toggleTheme: "தீம் மாற்று",
  devotee: "பக்தர்",
  appLanguage: "பயன்பாட்டு மொழி",
  appLanguageHint: "மெனுக்கள் மற்றும் லேபிள்களை மாற்றும். மந்திர சமஸ்கிருதம் எழுதப்பட்டவாறே இருக்கும்.",
  saveProfile: "சுயவிவரம் சேமி",
  signOut: "வெளியேறு",
  signInOrCreate: "உள்நுழை அல்லது கணக்கு உருவாக்கு",
  guestPreferences: "விருந்தினர் விருப்பங்கள் இந்த உலாவியில் இருக்கும்.",
  appearanceAndPlayback: "தோற்றம் மற்றும் பின்னணி",
  autoplayMedia: "ஊடகத்தை தானாக இயக்கு",
  notifications: "அறிவிப்புகள்",
  accountSecurity: "கணக்கு பாதுகாப்பு",
  gotraOptional: "கோத்திரம் அல்லது குடும்ப பாரம்பரியம் (விரும்பினால்)",
  yourNamePlaceholder: "உங்கள் பெயர்",
  enterIfKnown: "தெரிந்தால் மட்டும் உள்ளிடுங்கள்",
  ishtaKulaDevata: "இஷ்ட அல்லது குல தெய்வம் (விரும்பினால்)",
  chooseFamilyCalendar: "உங்கள் குடும்ப நாள்காட்டியைத் தேர்ந்தெடுங்கள்",
  signatureObservances: "முக்கிய சடங்குகள்",
  traditionsAndTemples: "பாரம்பரியங்கள் & கோயில்கள்",
  selectStateOrUt: "மாநிலம் அல்லது UT தேர்ந்தெடு",
  add: "சேர்",
  deleteReminder: "நினைவூட்டலை நீக்கு",
  personalSpiritualHome: "தனிப்பட்ட ஆன்மீக இல்லம்",
  completedOnDevice: "இந்த சாதனத்தில் முடிக்கப்பட்டது.",
  returnToHome: "முகப்புக்குத் திரும்பு",
  pageNotFound: "அய்யோ! பக்கம் கிடைக்கவில்லை",
  backHome: "முகப்புக்கு",
  beginWithMantra: "மந்திரத்துடன் தொடங்குங்கள்",
  watchLiveDarshan: "நேரடி தர்சனம் பாருங்கள்",
  openLibrary: "நூலகம் திற",
  todaysPanchang: "இன்றைய பஞ்சாங்கம்",
  dailyCalendar: "தினசரி நாள்காட்டி",
  useMyLocation: "என் இருப்பிடத்தைப் பயன்படுத்து",
  liveNow: "இப்போது நேரலை",
  refreshLiveStatus: "நேரலை நிலை புதுப்பி",
  sacredTextsHeritage: "புனித நூல்கள் & இந்து பாரம்பரியம்",
  readFullDetails: "முழு விவரங்களைப் படிக்க",
  priestSearch: "புரோகிதர் தேடல்",
  digitalJapaMala: "டிஜிட்டல் ஜப மala",
  reset: "மீட்டமை",
  closeFullImage: "முழு படம் மூடு",
  mantraScript: "மந்திர எழுத்து",
  useRegionalScript: "என் பிராந்திய எழுத்தைப் பயன்படுத்து",
  explaining: "விளக்குகிறது…",
  listenWithContext: "சூழலுடன் கேளுங்கள்",
  pravachanCulturalReading: "பிரவசன & கலாச்சார வாசிப்பு அறை",
  newsletterTagline: "அவ்வப்போது ஒரு சிந்தனை сообщение",
  newsletterDesc: "புதிய மந்திரங்கள், புனித நூல் சேர்ப்புகள் மற்றும் பயனுள்ள விழா வழிகாட்டுதல்—தினசரி இரைச்சல் இல்லாமல்.",
  emailAddressPlaceholder: "மின்னஞ்சல் முகவரி",
  subscribeAgreement: "மின்னஞ்சல் புதுப்பிப்புகளைப் பெற ஒப்புக்கொள்கிறேன். எந்த செய்தியிலிருந்தும் சந்தா ரத்து செய்யலாம்.",
  footerTagline: "மந்திர பயிற்சி, கோயில் தர்சனம், இந்து புனித இலக்கியம் மற்றும் அன்றாட பக்தி கற்றலுக்கான அமைதியான டிஜிட்டல் இடம்.",
  supportTheProject: "திட்டத்தை ஆதரிக்க",
  footerDisclaimer: "கல்வி பக்தி உள்ளடக்கம் · முகூர்த்தம் மற்றும் औपचारिक संस्कार தகுதியான பிராந்திய ஆதாரத்துடன் சரிபார்க்கவும்.",
  heroSubtitle: "உங்கள் தினசரி புனித பயணத்திற்கு அமைதியான இடம்.",
  heroDescription: "காலமless மந்திரங்களைக் கேளுங்கள், நேரடி கோயில் தர்சனம் அனுபवிக்கவும், இந்து scriptures ஒரு அழகாக இணைக்கப்பட்ட sanctuary-யில் படிக்கவும்.",
  sacredWisdomLiving: "புனித ஞானம் · உயிருள்ள பாரம்பரியம்",
  resources700: "700+ புனித resources",
  liveTempleDiscovery: "நேரலை கோயில் கண்டுபிடிப்பு",
  todaysIntention: "இன்றைய நோக்கம்",
  peaceInEveryBreath: "ஒவ்வொரு மூச்சிலும் அமைதி",
  readWisdom: "ஞானம் படிக்க",
  chooseSoundDarshan: "ஒலி, தarshan அல்லது scripture தேர்ந்தெடுங்கள்—ஒவ்வொரு அனுபवமும் பதிலளிக்கிறது, புதுப்பிக்கிறது, உங்களுடன் நகர்கிறது.",
  startListening: "கேட்க தொடங்குங்கள்",
  watchDarshan: "தarshan பாருங்கள்",
  readReflect: "படித்து சிந்திக்க",
  sacredTexts: "புனித நூல்கள்",
  designedAroundYou: "உங்களைச் சுற்றி வடிவமைக்கப்பட்டது",
  listenReadReflect: "கேள் · படி · சிந்தி",
  fastDiscovery: "விரைவு கண்டுபிடிப்பு",
  sanskritAndEnglish: "சமஸ்கிருதம் & ஆங்கிலம்",
  morningPractice: "காலை பயிற்சி",
  beginWithGayatri: "Gayatri உடன் தொடங்குங்கள்",
  enterTheTemple: "கோயிலில் நுழையுங்கள்",
  exploreTheGita: "Gita ஆராயுங்கள்",
  backToDivinityHarmony: "Divinity Harmony-க்குத் திரும்பு",
  practiceRemembered: "உங்கள் பயிற்சி, பாதுகாப்பாக நினைவில் வைக்கப்படுகிறது.",
  profileAcrossDevices: "உங்கள் சுயவிவரம், avatar மற்றும் ஆன்மீக விருப்பங்களை சாதனங்களில் இணைக்கவும்.",
  authPoweredBy: "அங்கீகாரம் மற்றும் கோப்பு சேமிப்பு Supabase மூலம்",
  authConfiguring: "கணக்கு சேவை கட்டமைக்கப்படுகிறது",
  guestAccessAvailable: "விருந்தினர் அணுகல் கிடைக்கும். உள்நுழைவை இயக்க Supabase deployment மாறிகளைச் சேர்க்கவும்.",
  signInWithEmail: "உங்கள் கணக்கில் பயன்படுத்திய மின்னஞ்சலால் உள்நுழையுங்கள்.",
  email: "மின்னஞ்சல்",
  password: "கடவுச்சொல்",
  forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
  createYourAccount: "உங்கள் கணக்கை உருவாக்குங்கள்",
  profileFollowsDevices: "உங்கள் சுயவிவரம் அனைத்து சாதனங்களிலும் உங்களுடன் இருக்கும்.",
  minEightChars: "குறைந்தது 8 எழுத்துகள்.",
  emailConfirmationNote: "உங்கள் Supabase project மூலம் மின்னஞ்சல் உறுதிப்படுத்தல் தேவைப்படலாம்.",
  listenAndChant: "கேட்டு ஜபம் செய்யுங்கள்",
  templeBroadcasts: "கோயில் ஒளிபரப்புகள்",
  readSanskritJapa: "சமஸ்கிருதத்தைப் படித்து, அர்த்தம் புரிந்து கொண்டு தினசரி ஜபத்தைத் தொடருங்கள்.",
  enterTempleStreams: "தானாகக் கண்டறியப்பட்டு புதுப்பிக்கப்படும் கோயில் ஸ்ட்ரீம்களில் நுழையுங்கள்.",
  exploreVedasHeritage: "Vedas, Gitas, Puranas, தத்துவம், வம்சம் மற்றும் இந்து பாரம்பரியத்தை ஆராயுங்கள்.",
  checkingLive: "நேரலை சரிபார்க்கப்படுகிறது",
  liveNowLower: "இப்போது நேரலை",
  streamsFound: "ஸ்ட்ரீம்கள் கண்டறியப்பட்டன",
  mantrasMetric: "மந்திரங்கள்",
  worksMetric: "நூல்கள்",
  moveNaturally: "ஒலி, புனித உருவம், அர்த்தம் மற்றும் மூலப் பாடத்திற்கிடையே இயல்பாக நகருங்கள். ஒவ்வொரு பாதையும் மொபைல் மற்றும் டெஸ்க்டாப்பில் அமைதியாகவும் பதிலளிக்கும் வகையிலும் இருக்கும்.",
  searchHundredsResources: "நூற்றுக்கணக்கான ஆதாரங்களைத் தேடுங்கள்.",
  originalTextContext: "மூலப் பாடம் மற்றும் தெளிவான சூழல்.",
  noNoiseMenus: "சத்தம் இல்லை, சிக்கலான மெனுக்கள் இல்லை—கேட்பது, தarshan மற்றும் நிலையான ஞானத்திற்கு நேரடி பாதை.",
  gayatriDetail: "தெளிவுக்கும் விழிப்புணர்வுக்கும் ஒரு பிரகாசமான வேதப் பிரார்த்தனை.",
  discoverDarshanStreams: "தற்போது ஒளிபரப்பப்படும் தarshan ஸ்ட்ரீம்களைக் கண்டறியுங்கள்.",
  gitaReadingDetail: "அமைதியான வாசிப்புக் காட்சியுடன் மூல-ஆதரவு அத்தியாயங்களைத் திறக்கவும்.",
  carryPractice: "பயிற்சியை உங்களுடன் எடுத்துச் செல்லுங்கள்.",
  loadingTodayDetails: "இன்றைய விவரங்கள் ஏற்றப்படுகின்றன…",
  panchangLocalized: "உள்ளூர் பanchang",
  nakshatra: "Nakshatra",
  tithi: "Tithi",
  yoga: "Yoga",
  karana: "Karana",
  starOf27: "27-இல் {n} நட்சத்திரம்",
  sunMoonCombination: "சூரிய–சந்திர இணைவு",
  halfTithiDivision: "அரை-திதி பிரிவு",
  sunrise: "சூரிய உதயம்",
  sunset: "சூரிய அஸ்தமனம்",
  moon: "சந்திரன்",
  locationNotSupported: "இந்த உலாவி இருப்பிடத்தை ஆதரிக்கவில்லை.",
  locationPermissionDenied: "இருப்பிட அனுமதி வழங்கப்படவில்லை. இந்தியாவின் கண்ணோட்டம் காட்டப்படுகிறது.",
  panchangCalendarAlt: "சூரியன், சந்திரன் மற்றும் நட்சத்திர வானியல் பanchang",
  templePriestDirectory: "கோயில் மற்றும் பurohit அடைவு",
  pleaseConfirmSubscribe: "மின்னஞ்சல் புதுப்பிப்புகளைப் பெற விரும்புகிறீர்கள் என்பதை உறுதிப்படுத்தவும்.",
  alreadySubscribed: "நீங்கள் ஏற்கனவே சந்தாதாரர்.",
  welcomeSubscribed: "வரவேற்கிறோம்—உங்கள் சந்தா உறுதிப்படுத்தப்பட்டது.",
  pleaseTryAgain: "தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
  liveLabel: "நேரலை",
};
