import type { AppLocale } from "@/hooks/use-locale";

export type VirtualPujaCopyKey =
  | "virtualWorship"
  | "ringToEnter"
  | "prepareSpace"
  | "markAllReady"
  | "begin"
  | "ringBell"
  | "soundOn"
  | "soundOff"
  | "guidance"
  | "offerNow"
  | "holdToOffer"
  | "complete"
  | "touchPoint"
  | "tilakaOffered"
  | "circleLamp"
  | "aartiComplete"
  | "previous"
  | "continue"
  | "finish"
  | "performAgain"
  | "completeMessage";

const copy: Record<AppLocale, Record<VirtualPujaCopyKey, string>> = {
  en: {
    virtualWorship: "Interactive virtual worship",
    ringToEnter: "Ring the bell to enter",
    prepareSpace: "Prepare the worship space",
    markAllReady: "Mark every material as ready",
    begin: "Begin the virtual puja",
    ringBell: "Ring the temple bell",
    soundOn: "Turn sound on",
    soundOff: "Turn sound off",
    guidance: "Ritual guidance",
    offerNow: "Offer now",
    holdToOffer: "Press and hold to offer",
    complete: "Offering complete",
    touchPoint: "Touch the glowing point on the deity image",
    tilakaOffered: "Tilaka offered",
    circleLamp: "Move the lamp in two full circles",
    aartiComplete: "Aarti complete",
    previous: "Previous",
    continue: "Continue",
    finish: "Finish",
    performAgain: "Perform again",
    completeMessage: "The offerings are complete. Sit quietly for a moment, then share prasada with gratitude.",
  },
  hi: {
    virtualWorship: "संवादात्मक आभासी पूजा",
    ringToEnter: "घंटी बजाकर मंदिर में प्रवेश करें",
    prepareSpace: "पूजन स्थल तैयार करें",
    markAllReady: "सभी सामग्रियों को तैयार चिह्नित करें",
    begin: "आभासी पूजा आरंभ करें",
    ringBell: "मंदिर की घंटी बजाएँ",
    soundOn: "ध्वनि चालू करें",
    soundOff: "ध्वनि बंद करें",
    guidance: "अनुष्ठान मार्गदर्शन",
    offerNow: "अब अर्पित करें",
    holdToOffer: "अर्पण के लिए दबाकर रखें",
    complete: "अर्पण पूर्ण",
    touchPoint: "देव प्रतिमा पर चमकते बिंदु को स्पर्श करें",
    tilakaOffered: "तिलक अर्पित",
    circleLamp: "दीपक को दो पूर्ण चक्रों में घुमाएँ",
    aartiComplete: "आरती पूर्ण",
    previous: "पिछला",
    continue: "आगे बढ़ें",
    finish: "समाप्त करें",
    performAgain: "पुनः पूजा करें",
    completeMessage: "अर्पण पूर्ण हो गए हैं। कुछ क्षण शांत बैठें, फिर कृतज्ञता से प्रसाद बाँटें।",
  },
  bn: {
    virtualWorship: "অংশগ্রহণমূলক ভার্চুয়াল পূজা",
    ringToEnter: "ঘণ্টা বাজিয়ে মন্দিরে প্রবেশ করুন",
    prepareSpace: "পূজার স্থান প্রস্তুত করুন",
    markAllReady: "সব উপকরণ প্রস্তুত হিসেবে চিহ্নিত করুন",
    begin: "ভার্চুয়াল পূজা শুরু করুন",
    ringBell: "মন্দিরের ঘণ্টা বাজান",
    soundOn: "শব্দ চালু করুন",
    soundOff: "শব্দ বন্ধ করুন",
    guidance: "পূজার নির্দেশনা",
    offerNow: "এখন নিবেদন করুন",
    holdToOffer: "নিবেদনের জন্য চেপে ধরে রাখুন",
    complete: "নিবেদন সম্পূর্ণ",
    touchPoint: "দেবমূর্তির ছবির উজ্জ্বল বিন্দুটি স্পর্শ করুন",
    tilakaOffered: "তিলক নিবেদন করা হয়েছে",
    circleLamp: "প্রদীপটি দুইবার সম্পূর্ণ ঘোরান",
    aartiComplete: "আরতি সম্পূর্ণ",
    previous: "আগের ধাপ",
    continue: "এগিয়ে যান",
    finish: "শেষ করুন",
    performAgain: "আবার পূজা করুন",
    completeMessage: "নিবেদন সম্পূর্ণ হয়েছে। কিছুক্ষণ নীরবে বসুন, তারপর কৃতজ্ঞতার সঙ্গে প্রসাদ ভাগ করুন।",
  },
  gu: {
    virtualWorship: "સહભાગી આભાસી પૂજા",
    ringToEnter: "ઘંટ વગાડી મંદિરમાં પ્રવેશ કરો",
    prepareSpace: "પૂજાનું સ્થાન તૈયાર કરો",
    markAllReady: "બધી સામગ્રી તૈયાર તરીકે ચિહ્નિત કરો",
    begin: "આભાસી પૂજા શરૂ કરો",
    ringBell: "મંદિરનો ઘંટ વગાડો",
    soundOn: "ધ્વનિ ચાલુ કરો",
    soundOff: "ધ્વનિ બંધ કરો",
    guidance: "વિધિ માર્ગદર્શન",
    offerNow: "હવે અર્પણ કરો",
    holdToOffer: "અર્પણ કરવા દબાવી રાખો",
    complete: "અર્પણ પૂર્ણ",
    touchPoint: "દેવતાની છબી પરના ચમકતા બિંદુને સ્પર્શ કરો",
    tilakaOffered: "તિલક અર્પણ થયું",
    circleLamp: "દીવો બે સંપૂર્ણ ચક્રમાં ફેરવો",
    aartiComplete: "આરતી પૂર્ણ",
    previous: "પાછલું પગલું",
    continue: "આગળ વધો",
    finish: "પૂર્ણ કરો",
    performAgain: "ફરી પૂજા કરો",
    completeMessage: "અર્પણ પૂર્ણ થયાં છે. થોડો સમય શાંતિથી બેસો, પછી કૃતજ્ઞતાથી પ્રસાદ વહેંચો.",
  },
  mr: {
    virtualWorship: "सहभागी आभासी पूजा",
    ringToEnter: "घंटा वाजवून मंदिरात प्रवेश करा",
    prepareSpace: "पूजेची जागा तयार करा",
    markAllReady: "सर्व साहित्य तयार असल्याची नोंद करा",
    begin: "आभासी पूजा सुरू करा",
    ringBell: "मंदिरातील घंटा वाजवा",
    soundOn: "ध्वनी सुरू करा",
    soundOff: "ध्वनी बंद करा",
    guidance: "पूजाविधी मार्गदर्शन",
    offerNow: "आता अर्पण करा",
    holdToOffer: "अर्पण करण्यासाठी दाबून ठेवा",
    complete: "अर्पण पूर्ण",
    touchPoint: "देवतेच्या प्रतिमेवरील चमकत्या बिंदूला स्पर्श करा",
    tilakaOffered: "तिलक अर्पण झाले",
    circleLamp: "दिवा दोन पूर्ण फेऱ्यांत फिरवा",
    aartiComplete: "आरती पूर्ण",
    previous: "मागील पाऊल",
    continue: "पुढे जा",
    finish: "समाप्त करा",
    performAgain: "पुन्हा पूजा करा",
    completeMessage: "अर्पण पूर्ण झाले आहे. काही क्षण शांत बसा, नंतर कृतज्ञतेने प्रसाद वाटा.",
  },
  ta: {
    virtualWorship: "பங்கேற்புடன் கூடிய மெய்நிகர் பூஜை",
    ringToEnter: "மணியை அடித்து கோயிலுக்குள் நுழையுங்கள்",
    prepareSpace: "பூஜை இடத்தைத் தயார் செய்யுங்கள்",
    markAllReady: "அனைத்து பொருட்களும் தயார் எனக் குறியிடுங்கள்",
    begin: "மெய்நிகர் பூஜையைத் தொடங்குங்கள்",
    ringBell: "கோயில் மணியை அடியுங்கள்",
    soundOn: "ஒலியை இயக்குங்கள்",
    soundOff: "ஒலியை நிறுத்துங்கள்",
    guidance: "பூஜை வழிகாட்டுதல்",
    offerNow: "இப்போது அர்ப்பணியுங்கள்",
    holdToOffer: "அர்ப்பணிக்க அழுத்திப் பிடியுங்கள்",
    complete: "அர்ப்பணம் நிறைவடைந்தது",
    touchPoint: "தெய்வப் படத்தில் ஒளிரும் புள்ளியைத் தொடுங்கள்",
    tilakaOffered: "திலகம் அர்ப்பணிக்கப்பட்டது",
    circleLamp: "தீபத்தை இரண்டு முழு சுற்றுகள் சுற்றுங்கள்",
    aartiComplete: "ஆரத்தி நிறைவடைந்தது",
    previous: "முந்தைய படி",
    continue: "தொடருங்கள்",
    finish: "நிறைவு செய்யுங்கள்",
    performAgain: "மீண்டும் பூஜை செய்யுங்கள்",
    completeMessage: "அர்ப்பணங்கள் நிறைவடைந்தன. சிறிது நேரம் அமைதியாக அமர்ந்து, பின்னர் நன்றியுடன் பிரசாதத்தைப் பகிருங்கள்.",
  },
  te: {
    virtualWorship: "పాల్గొనే ఆభాస పూజ",
    ringToEnter: "గంట మోగించి ఆలయంలోకి ప్రవేశించండి",
    prepareSpace: "పూజా స్థలాన్ని సిద్ధం చేయండి",
    markAllReady: "అన్ని సామగ్రి సిద్ధంగా ఉన్నట్లు గుర్తించండి",
    begin: "ఆభాస పూజను ప్రారంభించండి",
    ringBell: "ఆలయ గంటను మోగించండి",
    soundOn: "ధ్వనిని ప్రారంభించండి",
    soundOff: "ధ్వనిని ఆపండి",
    guidance: "పూజా విధి మార్గదర్శనం",
    offerNow: "ఇప్పుడు సమర్పించండి",
    holdToOffer: "సమర్పించడానికి నొక్కి పట్టుకోండి",
    complete: "సమర్పణ పూర్తయింది",
    touchPoint: "దేవత చిత్రంలోని ప్రకాశించే బిందువును తాకండి",
    tilakaOffered: "తిలకం సమర్పించబడింది",
    circleLamp: "దీపాన్ని రెండు పూర్తి వలయాల్లో తిప్పండి",
    aartiComplete: "హారతి పూర్తయింది",
    previous: "మునుపటి దశ",
    continue: "కొనసాగించండి",
    finish: "ముగించండి",
    performAgain: "మళ్లీ పూజ చేయండి",
    completeMessage: "సమర్పణలు పూర్తయ్యాయి. కొద్దిసేపు ప్రశాంతంగా కూర్చొని, తరువాత కృతజ్ఞతతో ప్రసాదాన్ని పంచండి.",
  },
  ml: {
    virtualWorship: "പങ്കാളിത്തമുള്ള സാങ്കൽപ്പിക പൂജ",
    ringToEnter: "മണി മുഴക്കി ക്ഷേത്രത്തിൽ പ്രവേശിക്കുക",
    prepareSpace: "പൂജാസ്ഥലം ഒരുക്കുക",
    markAllReady: "എല്ലാ സാമഗ്രികളും തയ്യാറെന്ന് അടയാളപ്പെടുത്തുക",
    begin: "സാങ്കൽപ്പിക പൂജ ആരംഭിക്കുക",
    ringBell: "ക്ഷേത്രമണി മുഴക്കുക",
    soundOn: "ശബ്ദം പ്രവർത്തിപ്പിക്കുക",
    soundOff: "ശബ്ദം നിർത്തുക",
    guidance: "പൂജാവിധി മാർഗനിർദേശം",
    offerNow: "ഇപ്പോൾ സമർപ്പിക്കുക",
    holdToOffer: "സമർപ്പിക്കാൻ അമർത്തിപ്പിടിക്കുക",
    complete: "സമർപ്പണം പൂർത്തിയായി",
    touchPoint: "ദേവതയുടെ ചിത്രത്തിലെ തിളങ്ങുന്ന ബിന്ദു സ്പർശിക്കുക",
    tilakaOffered: "തിലകം സമർപ്പിച്ചു",
    circleLamp: "ദീപം രണ്ട് പൂർണ്ണ വട്ടം ചുറ്റിക്കുക",
    aartiComplete: "ആരതി പൂർത്തിയായി",
    previous: "മുൻപത്തെ ഘട്ടം",
    continue: "തുടരുക",
    finish: "പൂർത്തിയാക്കുക",
    performAgain: "വീണ്ടും പൂജ ചെയ്യുക",
    completeMessage: "സമർപ്പണങ്ങൾ പൂർത്തിയായി. ഒരു നിമിഷം ശാന്തമായി ഇരിക്കുക, തുടർന്ന് നന്ദിയോടെ പ്രസാദം പങ്കിടുക.",
  },
  kn: {
    virtualWorship: "ಸಂವಾದಾತ್ಮಕ ಆಭಾಸಿ ಪೂಜೆ",
    ringToEnter: "ಗಂಟೆ ಬಾರಿಸಿ ದೇವಾಲಯ ಪ್ರವೇಶಿಸಿ",
    prepareSpace: "ಪೂಜಾ ಸ್ಥಳವನ್ನು ಸಿದ್ಧಪಡಿಸಿ",
    markAllReady: "ಎಲ್ಲ ಸಾಮಗ್ರಿಗಳು ಸಿದ್ಧವೆಂದು ಗುರುತಿಸಿ",
    begin: "ಆಭಾಸಿ ಪೂಜೆಯನ್ನು ಆರಂಭಿಸಿ",
    ringBell: "ದೇವಾಲಯದ ಗಂಟೆ ಬಾರಿಸಿ",
    soundOn: "ಧ್ವನಿಯನ್ನು ಚಾಲುಮಾಡಿ",
    soundOff: "ಧ್ವನಿಯನ್ನು ನಿಲ್ಲಿಸಿ",
    guidance: "ಪೂಜಾ ವಿಧಿ ಮಾರ್ಗದರ್ಶನ",
    offerNow: "ಈಗ ಅರ್ಪಿಸಿ",
    holdToOffer: "ಅರ್ಪಿಸಲು ಒತ್ತಿಹಿಡಿಯಿರಿ",
    complete: "ಅರ್ಪಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ",
    touchPoint: "ದೇವರ ಚಿತ್ರದ ಮೇಲಿನ ಹೊಳೆಯುವ ಬಿಂದುವನ್ನು ಸ್ಪರ್ಶಿಸಿ",
    tilakaOffered: "ತಿಲಕ ಅರ್ಪಿಸಲಾಗಿದೆ",
    circleLamp: "ದೀಪವನ್ನು ಎರಡು ಪೂರ್ಣ ಸುತ್ತು ತಿರುಗಿಸಿ",
    aartiComplete: "ಆರತಿ ಪೂರ್ಣಗೊಂಡಿದೆ",
    previous: "ಹಿಂದಿನ ಹಂತ",
    continue: "ಮುಂದುವರಿಸಿ",
    finish: "ಮುಗಿಸಿ",
    performAgain: "ಮತ್ತೆ ಪೂಜೆ ಮಾಡಿ",
    completeMessage: "ಅರ್ಪಣೆಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ. ಸ್ವಲ್ಪ ಹೊತ್ತು ಶಾಂತವಾಗಿ ಕುಳಿತು, ನಂತರ ಕೃತಜ್ಞತೆಯಿಂದ ಪ್ರಸಾದವನ್ನು ಹಂಚಿ.",
  },
  or: {
    virtualWorship: "ଅଂଶଗ୍ରହଣମୂଳକ ଆଭାସୀ ପୂଜା",
    ringToEnter: "ଘଣ୍ଟି ବଜାଇ ମନ୍ଦିରରେ ପ୍ରବେଶ କରନ୍ତୁ",
    prepareSpace: "ପୂଜା ସ୍ଥାନ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
    markAllReady: "ସମସ୍ତ ସାମଗ୍ରୀ ପ୍ରସ୍ତୁତ ବୋଲି ଚିହ୍ନିତ କରନ୍ତୁ",
    begin: "ଆଭାସୀ ପୂଜା ଆରମ୍ଭ କରନ୍ତୁ",
    ringBell: "ମନ୍ଦିର ଘଣ୍ଟି ବଜାନ୍ତୁ",
    soundOn: "ଧ୍ୱନି ଚାଲୁ କରନ୍ତୁ",
    soundOff: "ଧ୍ୱନି ବନ୍ଦ କରନ୍ତୁ",
    guidance: "ପୂଜାବିଧି ମାର୍ଗଦର୍ଶନ",
    offerNow: "ଏବେ ଅର୍ପଣ କରନ୍ତୁ",
    holdToOffer: "ଅର୍ପଣ ପାଇଁ ଦବାଇ ଧରନ୍ତୁ",
    complete: "ଅର୍ପଣ ସମ୍ପୂର୍ଣ୍ଣ",
    touchPoint: "ଦେବତାଙ୍କ ଛବିର ଉଜ୍ଜ୍ୱଳ ବିନ୍ଦୁକୁ ସ୍ପର୍ଶ କରନ୍ତୁ",
    tilakaOffered: "ତିଳକ ଅର୍ପିତ",
    circleLamp: "ଦୀପକୁ ଦୁଇଟି ପୂର୍ଣ୍ଣ ଚକ୍ରରେ ବୁଲାନ୍ତୁ",
    aartiComplete: "ଆରତି ସମ୍ପୂର୍ଣ୍ଣ",
    previous: "ପୂର୍ବ ପଦକ୍ଷେପ",
    continue: "ଆଗକୁ ବଢ଼ନ୍ତୁ",
    finish: "ସମାପ୍ତ କରନ୍ତୁ",
    performAgain: "ପୁଣି ପୂଜା କରନ୍ତୁ",
    completeMessage: "ଅର୍ପଣ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଛି। କିଛି ସମୟ ଶାନ୍ତ ହୋଇ ବସନ୍ତୁ, ପରେ କୃତଜ୍ଞତାର ସହ ପ୍ରସାଦ ବାଣ୍ଟନ୍ତୁ।",
  },
  pa: {
    virtualWorship: "ਭਾਗੀਦਾਰੀ ਵਾਲੀ ਆਭਾਸੀ ਪੂਜਾ",
    ringToEnter: "ਘੰਟੀ ਵਜਾ ਕੇ ਮੰਦਰ ਵਿੱਚ ਪ੍ਰਵੇਸ਼ ਕਰੋ",
    prepareSpace: "ਪੂਜਾ ਦਾ ਸਥਾਨ ਤਿਆਰ ਕਰੋ",
    markAllReady: "ਸਾਰੀ ਸਮੱਗਰੀ ਤਿਆਰ ਵਜੋਂ ਨਿਸ਼ਾਨ ਲਗਾਓ",
    begin: "ਆਭਾਸੀ ਪੂਜਾ ਸ਼ੁਰੂ ਕਰੋ",
    ringBell: "ਮੰਦਰ ਦੀ ਘੰਟੀ ਵਜਾਓ",
    soundOn: "ਧੁਨੀ ਚਾਲੂ ਕਰੋ",
    soundOff: "ਧੁਨੀ ਬੰਦ ਕਰੋ",
    guidance: "ਪੂਜਾ ਵਿਧੀ ਮਾਰਗਦਰਸ਼ਨ",
    offerNow: "ਹੁਣ ਅਰਪਣ ਕਰੋ",
    holdToOffer: "ਅਰਪਣ ਲਈ ਦਬਾ ਕੇ ਰੱਖੋ",
    complete: "ਅਰਪਣ ਪੂਰਾ ਹੋਇਆ",
    touchPoint: "ਦੇਵਤਾ ਦੀ ਤਸਵੀਰ ਉੱਤੇ ਚਮਕਦੇ ਬਿੰਦੂ ਨੂੰ ਛੂਹੋ",
    tilakaOffered: "ਤਿਲਕ ਅਰਪਿਤ ਕੀਤਾ",
    circleLamp: "ਦੀਵੇ ਨੂੰ ਦੋ ਪੂਰੇ ਚੱਕਰਾਂ ਵਿੱਚ ਘੁਮਾਓ",
    aartiComplete: "ਆਰਤੀ ਪੂਰੀ ਹੋਈ",
    previous: "ਪਿਛਲਾ ਪੜਾਅ",
    continue: "ਅੱਗੇ ਵਧੋ",
    finish: "ਸਮਾਪਤ ਕਰੋ",
    performAgain: "ਦੁਬਾਰਾ ਪੂਜਾ ਕਰੋ",
    completeMessage: "ਅਰਪਣ ਪੂਰੇ ਹੋ ਗਏ ਹਨ। ਕੁਝ ਪਲ ਸ਼ਾਂਤ ਬੈਠੋ, ਫਿਰ ਸ਼ੁਕਰਾਨੇ ਨਾਲ ਪ੍ਰਸਾਦ ਵੰਡੋ।",
  },
  as: {
    virtualWorship: "অংশগ্ৰহণমূলক আভাসী পূজা",
    ringToEnter: "ঘণ্টা বজাই মন্দিৰত প্ৰৱেশ কৰক",
    prepareSpace: "পূজাৰ স্থান প্ৰস্তুত কৰক",
    markAllReady: "সকলো সামগ্ৰী প্ৰস্তুত বুলি চিহ্নিত কৰক",
    begin: "আভাসী পূজা আৰম্ভ কৰক",
    ringBell: "মন্দিৰৰ ঘণ্টা বজাওক",
    soundOn: "ধ্বনি চালু কৰক",
    soundOff: "ধ্বনি বন্ধ কৰক",
    guidance: "পূজাবিধিৰ পথনিৰ্দেশ",
    offerNow: "এতিয়া অৰ্পণ কৰক",
    holdToOffer: "অৰ্পণ কৰিবলৈ টিপি ধৰি ৰাখক",
    complete: "অৰ্পণ সম্পূৰ্ণ",
    touchPoint: "দেৱতাৰ ছবিৰ উজ্জ্বল বিন্দুটো স্পৰ্শ কৰক",
    tilakaOffered: "তিলক অৰ্পণ কৰা হ'ল",
    circleLamp: "চাকিটো দুটা সম্পূৰ্ণ চক্ৰত ঘূৰাওক",
    aartiComplete: "আৰতি সম্পূৰ্ণ",
    previous: "পূৰ্বৰ ধাপ",
    continue: "আগবাঢ়ক",
    finish: "সমাপ্ত কৰক",
    performAgain: "পুনৰ পূজা কৰক",
    completeMessage: "অৰ্পণসমূহ সম্পূৰ্ণ হৈছে। কিছু সময় শান্তভাৱে বহক, তাৰ পিছত কৃতজ্ঞতাৰে প্ৰসাদ ভাগ কৰক।",
  },
};

export function virtualPujaCopy(locale: AppLocale, key: VirtualPujaCopyKey): string {
  return copy[locale][key];
}
