import { useCallback, useEffect, useMemo, useState } from 'react';
import { ExternalLink, Loader2, Music2, PlayCircle, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';

type Recording={videoId:string;title:string;channelTitle:string;duration:string;thumbnailUrl:string;url:string;embedUrl:string};
export default function YouTubeMantraPlayer({title}:{title:string}){
 const[items,setItems]=useState<Recording[]>([]);const[selected,setSelected]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=useCallback(()=>{const controller=new AbortController();setLoading(true);setError('');fetch(`/api/mantra-recordings?title=${encodeURIComponent(title)}`,{signal:controller.signal}).then(r=>r.json().then(data=>({ok:r.ok,data}))).then(({ok,data})=>{if(!ok)throw new Error(data.error||'Recording search failed');setItems(data.items||[]);setSelected(0);if(!(data.items||[]).length)setError('No embeddable recording was found right now.');}).catch(e=>{if(e.name!=='AbortError')setError(e.message||'YouTube recordings are temporarily unavailable.');}).finally(()=>setLoading(false));return controller;},[title]);
 useEffect(()=>{const controller=load();return()=>controller.abort();},[load]);
 const current=items[selected];const searchUrl=useMemo(()=>`https://www.youtube.com/results?search_query=${encodeURIComponent(`${title} devotional mantra full`)}`,[title]);
 return <section className="mt-6 overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="flex flex-col gap-3 border-b bg-gradient-to-r from-red-50 to-orange-50 p-5 dark:from-red-950/25 dark:to-orange-950/20 sm:flex-row sm:items-center sm:justify-between"><div><p className="flex items-center text-xs font-semibold uppercase tracking-[.18em] text-red-700"><Music2 className="mr-2 h-4 w-4"/>Devotional recording</p><h3 className="mt-1 text-lg font-bold">{title}</h3><p className="mt-1 text-xs text-muted-foreground">Played through YouTube’s official embedded player—not downloaded or converted to MP3.</p></div><Button size="sm" variant="outline" onClick={()=>load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?'animate-spin':''}`}/>Find recordings</Button></div>
 {loading?<div className="flex min-h-56 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-orange-700"/></div>:current?<><div className="aspect-video min-h-[200px] bg-black"><iframe key={current.videoId} className="h-full w-full" src={current.embedUrl} title={current.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{current.title}</p><p className="mt-1 text-xs text-muted-foreground">{current.channelTitle}{current.duration?` · ${current.duration}`:''}</p></div><a href={current.url} target="_blank" rel="noopener noreferrer" className="shrink-0 text-xs font-medium text-red-700 hover:underline">YouTube<ExternalLink className="ml-1 inline h-3 w-3"/></a></div>{items.length>1&&<div className="mt-4 flex gap-3 overflow-x-auto pb-2">{items.map((item,index)=><button type="button" key={item.videoId} onClick={()=>setSelected(index)} className={`min-w-44 rounded-xl border p-2 text-left transition ${index===selected?'border-red-600 bg-red-50 ring-1 ring-red-600 dark:bg-red-950/20':'hover:border-orange-300'}`}><div className="flex items-center gap-2"><PlayCircle className="h-4 w-4 shrink-0 text-red-600"/><span className="line-clamp-2 text-xs font-medium">{item.title}</span></div></button>)}</div>}</div></>:<div className="p-8 text-center"><p className="text-sm text-muted-foreground">{error}</p><Button asChild className="mt-4"><a href={searchUrl} target="_blank" rel="noopener noreferrer">Search this mantra on YouTube<ExternalLink className="ml-2 h-4 w-4"/></a></Button></div>}
 </section>;
}
