import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, Loader2, Mail, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/components/ui/use-toast';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/use-auth';

interface Props{onComplete?:()=>void}
export default function SplashScreen({onComplete}:Props){
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[busy,setBusy]=useState(false);const{toast}=useToast();const navigate=useNavigate();const{user,configured}=useAuth();
 useEffect(()=>{if(user)navigate('/settings',{replace:true});},[user,navigate]);
 const finish=()=>{onComplete?.();navigate('/',{replace:true});};
 const login=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(error){toast({title:'Unable to sign in',description:error.message,variant:'destructive'});return;}toast({title:'Welcome back',description:'Your spiritual profile is ready.'});finish();};
 const register=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;if(password.length<8){toast({title:'Password is too short',description:'Use at least 8 characters.',variant:'destructive'});return;}setBusy(true);const{data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{display_name:name.trim()}}});setBusy(false);if(error){toast({title:'Unable to create account',description:error.message,variant:'destructive'});return;}if(!data.session)toast({title:'Check your email',description:'Open the confirmation link, then return to sign in.'});else finish();};
 const reset=async()=>{if(!supabase||!email.trim()){toast({title:'Enter your email first'});return;}const{error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/settings`});toast({title:error?'Reset unavailable':'Password reset sent',description:error?.message||'Check your inbox for the secure reset link.',variant:error?'destructive':'default'});};
 return <div className="min-h-screen bg-[#fff8ed] md:grid md:grid-cols-2 dark:bg-background"><div className="relative hidden overflow-hidden bg-gradient-to-br from-orange-950 via-red-950 to-amber-900 p-12 text-white md:flex md:flex-col md:justify-between"><div className="absolute -right-24 top-16 h-80 w-80 rounded-full border border-amber-300/20 shadow-[0_0_0_45px_rgba(251,191,36,.06),0_0_0_90px_rgba(251,191,36,.04)]"/><Link to="/" className="relative inline-flex items-center text-sm text-orange-100/80 hover:text-white"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Divinity Harmony</Link><div className="relative max-w-xl"><span className="text-7xl text-amber-300">ॐ</span><h1 className="mt-6 text-5xl font-bold leading-tight">Your practice,<br/>remembered securely.</h1><p className="mt-5 max-w-lg text-lg leading-8 text-orange-100/75">Keep your profile, avatar and spiritual preferences connected across devices.</p></div><p className="relative flex items-center text-xs text-orange-100/60"><ShieldCheck className="mr-2 h-4 w-4"/>Authentication and file storage powered by Supabase</p></div><div className="flex items-center justify-center p-5 py-12"><div className="w-full max-w-md"><div className="mb-8 text-center md:hidden"><span className="text-5xl text-orange-700">ॐ</span><h1 className="mt-3 text-3xl font-bold">Divinity Harmony</h1></div>
 {!configured?<Card className="border-amber-200 bg-amber-50"><CardHeader><CardTitle>Account service is being configured</CardTitle><CardDescription>Guest access remains available. Add the Supabase deployment variables to enable login.</CardDescription></CardHeader><CardFooter><Button className="w-full" onClick={finish}>Continue as guest</Button></CardFooter></Card>:
 <Card className="rounded-3xl border-orange-950/10 shadow-xl"><Tabs defaultValue="login"><TabsList className="m-6 mb-0 grid w-auto grid-cols-2"><TabsTrigger value="login">Sign in</TabsTrigger><TabsTrigger value="register">Create account</TabsTrigger></TabsList><TabsContent value="login"><CardHeader><CardTitle>Welcome back</CardTitle><CardDescription>Sign in with the email used for your account.</CardDescription></CardHeader><CardContent><form onSubmit={login} className="space-y-4"><div className="space-y-2"><Label htmlFor="login-email">Email</Label><Input id="login-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div><div className="space-y-2"><div className="flex justify-between"><Label htmlFor="login-password">Password</Label><button type="button" onClick={reset} className="text-xs text-orange-700 hover:underline">Forgot password?</button></div><Input id="login-password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></div><Button disabled={busy} className="w-full">{busy&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Sign in</Button></form></CardContent></TabsContent><TabsContent value="register"><CardHeader><CardTitle>Create your account</CardTitle><CardDescription>Your profile will follow you across devices.</CardDescription></CardHeader><CardContent><form onSubmit={register} className="space-y-4"><div className="space-y-2"><Label htmlFor="register-name">Display name</Label><Input id="register-name" required value={name} onChange={e=>setName(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="register-email">Email</Label><Input id="register-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="register-password">Password</Label><Input id="register-password" type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/><p className="text-xs text-muted-foreground">Minimum 8 characters.</p></div><Button disabled={busy} className="w-full">{busy&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Create account</Button></form></CardContent></TabsContent><CardFooter className="flex-col gap-3 border-t pt-5"><Button variant="ghost" onClick={finish} className="w-full">Continue as guest</Button><p className="flex items-center text-[11px] text-muted-foreground"><Mail className="mr-1 h-3 w-3"/>Email confirmation may be required by your Supabase project.</p></CardFooter></Tabs></Card>}
 </div></div></div>;
}
